In [1]:
import pandas as pd 
import numpy as np 
import scipy.stats as stats
import plotly.graph_objects as go 
import plotly.express  as px

In [2]:
train_df = pd.read_csv(r"C:\potfolio\Heart_disease_prediction\data\raw\train.csv")
train_df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Age                      630000 non-null  int64
 2   Sex                      630000 non-null  int64
 3   Chest pain type          630000 non-null  int64
 4   BP                       630000 non-null  int64
 5   Cholesterol              630000 non-null  int64
 6   FBS over 120             630000 non-null  int64
 7   EKG results              630000 non-null  int64
 8   Max HR                   630000 non-null  int64
 9   Exercise angina          630000 non-null  int64
 10  ST depression            630000 non-null  float64
 11  Slope of ST              630000 non-null  int64
 12  Number of vessels fluro  630000 non-null  int64
 13  Thallium                 630000 non-null  int64
 14  Heart Disease            630000 non-null  object
dtypes: float64(1), int64(13), object(1)
memory usage: 72.1+ MB

In [6]:
class_balance = train_df["Heart Disease"].value_counts().reset_index()
class_balance.columns = ["Type", "value"]
class_balance

       Type   value
0   Absence  347546
1  Presence  282454

In [7]:
fig = go.Figure()
fig.add_trace(
    go.Pie(labels=class_balance["Type"], values=class_balance["value"])
)
fig.update_layout(
    title = "Pie chart of class"
)
fig.show()

In [8]:
train_df.columns

Index(['id', 'Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol',
       'FBS over 120', 'EKG results', 'Max HR', 'Exercise angina',
       'ST depression', 'Slope of ST', 'Number of vessels fluro', 'Thallium',
       'Heart Disease'],
      dtype='object')

In [18]:
fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x = train_df["Age"],
        marker=dict(
            line = dict(color = "Black", width = 1),
            color = "skyblue"
            ),

        nbinsx=25
    )
)

fig.update_layout(
    title = "Age distribution",
    xaxis_title = "Age scale",
    yaxis_title = "Frequency"
)

fig.show()

In [22]:
gender_based_positive = train_df.groupby("Sex")["Heart Disease"].value_counts().reset_index()
gender_based_positive["Sex"] = gender_based_positive["Sex"].replace({0:"Female", 1:"Male"})
gender_based_positive[gender_based_positive["Heart Disease"] == "Presence"]

      Sex Heart Disease   count
1  Female      Presence   32127
2    Male      Presence  250327

In [23]:
fig = go.Figure()

fig.add_trace(
    go.Bar(
        x = gender_based_positive["Sex"],
        y = gender_based_positive["count"]
    )
)

fig.update_layout(
    title = "Comparison of Presence of Heart Disease between Gender",
    xaxis_title = "Gender",
    yaxis_title = "Count"
)
fig.show()

In [24]:
train_df.head()

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,Presence
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,Absence
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,Absence
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,Absence
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,Presence

In [25]:
train_df["Heart Disease"] = train_df["Heart Disease"].replace({"Presence" : 1, "Absence" : 0})
train_df.head()

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_12668\1280945402.py:1: FutureWarning:

Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

,id,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,0,58,1,4,152,239,0,0,158,1,3.6,2,2,7,1
1,1,52,1,1,125,325,0,2,171,0,0.0,1,0,3,0
2,2,56,0,2,160,188,0,2,151,0,0.0,1,0,3,0
3,3,44,0,3,134,229,0,2,150,0,1.0,2,0,3,0
4,4,58,1,4,140,234,0,2,125,1,3.8,2,3,3,1

In [26]:
train_df.to_csv(r"C:\potfolio\Heart_disease_prediction\data\processed_data\processed_train_df.csv")