In [1]:
import pandas as pd 
import numpy as np

In [7]:
file_10 = pd.read_csv(r"C:\potfolio\Wind_turbin_fault_detection_and_generation_loss\data\raw\Wind Farm A\datasets\10.csv", sep=";")
file_10.head()

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
0,2022-10-09 08:40:00,10,0,train,4,20.0,265.7,19.4,2.6,2.6,...,-1946.0,0.0,0.0,-1371.0,-1946.0,1.8,2.0,0.0,0.2,23.0
1,2022-10-09 08:50:00,10,1,train,4,20.0,244.9,-11.8,2.6,2.6,...,-1850.0,0.0,0.0,-1309.0,-1850.0,1.8,2.0,1.5,0.1,23.0
2,2022-10-09 09:00:00,10,2,train,4,20.0,299.5,42.7,2.5,2.5,...,-1851.0,0.0,0.0,-1349.0,-1851.0,1.6,2.0,0.0,0.7,23.0
3,2022-10-09 09:10:00,10,3,train,4,20.0,280.2,23.5,2.5,2.5,...,-1824.0,0.0,0.0,-1326.0,-1824.0,1.7,1.9,1.5,0.1,23.0
4,2022-10-09 09:20:00,10,4,train,4,20.0,281.1,24.3,2.7,2.7,...,-1838.0,0.0,0.0,-1324.0,-1838.0,1.9,2.1,1.8,0.1,23.0

In [8]:
file_92 = pd.read_csv(r"C:\potfolio\Wind_turbin_fault_detection_and_generation_loss\data\raw\Wind Farm A\datasets\92.csv",sep =";")
file_92.head()

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
0,2022-04-04 02:30:00,11,0,train,0,15.0,257.0,-1.8,2.7,2.7,...,-375.0,0.0,0.0,-885.0,-375.0,2.0,2.2,1.6,0.1,17.0
1,2022-04-04 02:40:00,11,1,train,0,15.0,267.3,13.4,2.6,2.6,...,-226.0,0.0,0.0,-822.0,-226.0,1.9,2.2,1.5,0.2,17.0
2,2022-04-04 02:50:00,11,2,train,0,15.0,280.9,27.0,3.0,3.0,...,-360.0,0.0,0.0,-884.0,-360.0,2.2,2.6,1.7,0.2,17.0
3,2022-04-04 03:00:00,11,3,train,0,15.0,256.5,6.8,2.8,2.8,...,-356.0,0.0,0.0,-869.0,-356.0,2.2,2.6,1.8,0.2,17.0
4,2022-04-04 03:10:00,11,4,train,0,15.0,260.2,7.4,3.4,3.4,...,-13.0,771.0,0.0,20.0,759.0,4.5,12.2,2.1,3.5,17.0

In [10]:
file_92.iloc[:, -20:].head()

,sensor_37_avg,sensor_38_avg,sensor_39_avg,sensor_40_avg,sensor_41_avg,sensor_42_avg,sensor_43_avg,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
0,33.0,64.0,72.0,62.0,27.0,258.8,26.0,-885.0,0.0,0.0,-375.0,0.0,0.0,-885.0,-375.0,2.0,2.2,1.6,0.1,17.0
1,32.0,64.0,72.0,62.0,27.0,253.9,26.0,-822.0,0.0,0.0,-226.0,0.0,0.0,-822.0,-226.0,1.9,2.2,1.5,0.2,17.0
2,31.0,64.0,72.0,62.0,27.0,253.9,26.0,-884.0,0.0,0.0,-360.0,0.0,0.0,-884.0,-360.0,2.2,2.6,1.7,0.2,17.0
3,31.0,64.0,72.0,62.0,27.0,249.7,25.0,-869.0,0.0,0.0,-356.0,0.0,0.0,-869.0,-356.0,2.2,2.6,1.8,0.2,17.0
4,31.0,63.0,72.0,62.0,27.0,252.9,25.0,-804.0,824.0,0.0,-13.0,771.0,0.0,20.0,759.0,4.5,12.2,2.1,3.5,17.0

In [11]:
event_details = pd.read_csv(r"C:\potfolio\Wind_turbin_fault_detection_and_generation_loss\data\raw\Wind Farm A\event_info.csv",sep = ";")
event_details.head()

,asset,event_id,event_label,event_start,event_start_id,event_end,event_end_id,event_description
0,11,68,anomaly,2023-07-28 13:20:00,52063,2023-08-11 13:10:00,54076,Transformer failure
1,21,22,anomaly,2023-08-12 09:50:00,51888,2023-08-19 10:00:00,52892,Hydraulic group
2,21,72,anomaly,2023-10-10 08:40:00,52497,2023-10-17 08:40:00,53505,Gearbox failure
3,0,73,anomaly,2023-06-10 11:40:00,52745,2023-06-17 11:40:00,53753,Hydraulic group
4,0,0,anomaly,2023-08-06 06:10:00,52436,2023-08-20 06:10:00,54447,Generator bearing failure

In [12]:
event_details["asset"].value_counts()

asset
0     5
10    5
11    4
21    4
13    4
Name: count, dtype: int64

In [13]:
features_details = pd.read_csv(r"C:\potfolio\Wind_turbin_fault_detection_and_generation_loss\data\raw\Wind Farm A\feature_description.csv",sep= ";")
features_details.head()

,sensor_name,statistics_type,description,unit,is_angle,is_counter
0,sensor_0,average,Ambient temperature,�C,False,False
1,sensor_1,average,Wind absolute direction,�,True,False
2,sensor_2,average,Wind relative direction,�,True,False
3,wind_speed_3,"maximum,minimum,average,std_dev",Windspeed,m/s,False,False
4,wind_speed_4,average,Estimated windspeed,m/s,False,False

In [14]:
features_details["sensor_name"].value_counts()

sensor_name
sensor_0             1
sensor_40            1
power_29             1
power_30             1
sensor_31            1
sensor_32            1
sensor_33            1
sensor_34            1
sensor_35            1
sensor_36            1
sensor_37            1
sensor_38            1
sensor_39            1
sensor_41            1
sensor_1             1
sensor_42            1
sensor_43            1
sensor_44            1
sensor_45            1
sensor_46            1
sensor_47            1
sensor_48            1
sensor_49            1
sensor_50            1
sensor_51            1
sensor_52            1
reactive_power_28    1
reactive_power_27    1
sensor_26            1
sensor_25            1
sensor_2             1
wind_speed_3         1
wind_speed_4         1
sensor_5             1
sensor_6             1
sensor_7             1
sensor_8             1
sensor_9             1
sensor_10            1
sensor_11            1
sensor_12            1
sensor_13            1
sensor_14            1
sensor_15            1
sensor_16            1
sensor_17            1
sensor_18            1
sensor_19            1
sensor_20            1
sensor_21            1
sensor_22            1
sensor_23            1
sensor_24            1
sensor_53            1
Name: count, dtype: int64

In [15]:
file_0 = pd.read_csv(r"C:\potfolio\Wind_turbin_fault_detection_and_generation_loss\data\raw\Wind Farm A\datasets\0.csv",sep = ";")
file_0.head()

,time_stamp,asset_id,id,train_test,status_type_id,sensor_0_avg,sensor_1_avg,sensor_2_avg,wind_speed_3_avg,wind_speed_4_avg,...,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,sensor_52_avg,sensor_52_max,sensor_52_min,sensor_52_std,sensor_53_avg
0,2022-08-04 06:10:00,0,0,train,0,22.0,302.9,129.4,1.7,1.7,...,-496.0,0.0,0.0,-1280.0,-496.0,0.0,0.0,0.0,0.0,26.0
1,2022-08-04 06:20:00,0,1,train,0,22.0,307.1,133.6,1.7,1.7,...,-490.0,0.0,0.0,-1278.0,-490.0,0.0,0.0,0.0,0.0,25.0
2,2022-08-04 06:30:00,0,2,train,0,22.0,340.6,167.1,0.9,0.9,...,-490.0,0.0,0.0,-1356.0,-490.0,0.0,0.0,0.0,0.0,25.0
3,2022-08-04 06:40:00,0,3,train,0,22.0,124.4,-49.1,1.5,1.5,...,-509.0,0.0,0.0,-1274.0,-509.0,0.0,0.0,0.0,0.0,26.0
4,2022-08-04 06:50:00,0,4,train,0,22.0,66.2,-107.3,1.0,1.0,...,-499.0,0.0,0.0,-1284.0,-499.0,0.0,0.0,0.0,0.0,26.0

In [16]:
file_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54986 entries, 0 to 54985
Data columns (total 86 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   time_stamp             54986 non-null  object
 1   asset_id               54986 non-null  int64
 2   id                     54986 non-null  int64
 3   train_test             54986 non-null  object
 4   status_type_id         54986 non-null  int64
 5   sensor_0_avg           54986 non-null  float64
 6   sensor_1_avg           54986 non-null  float64
 7   sensor_2_avg           54986 non-null  float64
 8   wind_speed_3_avg       54986 non-null  float64
 9   wind_speed_4_avg       54986 non-null  float64
 10  wind_speed_3_max       54986 non-null  float64
 11  wind_speed_3_min       54986 non-null  float64
 12  wind_speed_3_std       54986 non-null  float64
 13  sensor_5_avg           54986 non-null  float64
 14  sensor_5_max           54986 non-null  float64
 15  sensor_5_min           54986 non-null  float64
 16  sensor_5_std           54986 non-null  float64
 17  sensor_6_avg           54986 non-null  float64
 18  sensor_7_avg           54986 non-null  float64
 19  sensor_8_avg           54986 non-null  float64
 20  sensor_9_avg           54986 non-null  float64
 21  sensor_10_avg          54986 non-null  float64
 22  sensor_11_avg          54986 non-null  float64
 23  sensor_12_avg          54986 non-null  float64
 24  sensor_13_avg          54986 non-null  float64
 25  sensor_14_avg          54985 non-null  float64
 26  sensor_15_avg          54986 non-null  float64
 27  sensor_16_avg          54986 non-null  float64
 28  sensor_17_avg          54986 non-null  float64
 29  sensor_18_avg          54986 non-null  float64
 30  sensor_18_max          54986 non-null  float64
 31  sensor_18_min          54986 non-null  float64
 32  sensor_18_std          54986 non-null  float64
 33  sensor_19_avg          54986 non-null  float64
 34  sensor_20_avg          54986 non-null  float64
 35  sensor_21_avg          54986 non-null  float64
 36  sensor_22_avg          54985 non-null  float64
 37  sensor_23_avg          54986 non-null  float64
 38  sensor_24_avg          54986 non-null  float64
 39  sensor_25_avg          54986 non-null  float64
 40  sensor_26_avg          54986 non-null  float64
 41  reactive_power_27_avg  54986 non-null  float64
 42  reactive_power_27_max  54986 non-null  float64
 43  reactive_power_27_min  54986 non-null  float64
 44  reactive_power_27_std  54986 non-null  float64
 45  reactive_power_28_avg  54986 non-null  float64
 46  reactive_power_28_max  54986 non-null  float64
 47  reactive_power_28_min  54986 non-null  float64
 48  reactive_power_28_std  54986 non-null  float64
 49  power_29_avg           54986 non-null  float64
 50  power_29_max           54986 non-null  float64
 51  power_29_min           54986 non-null  float64
 52  power_29_std           54986 non-null  float64
 53  power_30_avg           54986 non-null  float64
 54  power_30_max           54986 non-null  float64
 55  power_30_min           54986 non-null  float64
 56  power_30_std           54986 non-null  float64
 57  sensor_31_avg          54986 non-null  float64
 58  sensor_31_max          54986 non-null  float64
 59  sensor_31_min          54986 non-null  float64
 60  sensor_31_std          54986 non-null  float64
 61  sensor_32_avg          54986 non-null  float64
 62  sensor_33_avg          54986 non-null  float64
 63  sensor_34_avg          54986 non-null  float64
 64  sensor_35_avg          54986 non-null  float64
 65  sensor_36_avg          54986 non-null  float64
 66  sensor_37_avg          54986 non-null  float64
 67  sensor_38_avg          54986 non-null  float64
 68  sensor_39_avg          54986 non-null  float64
 69  sensor_40_avg          54986 non-null  float64
 70  sensor_41_avg          54986 non-null  float64
 71  sensor_42_avg          54986 non-null  float64
 72  sensor_43_avg          54986 non-null  float64
 73  sensor_44              54986 non-null  float64
 74  sensor_45              54986 non-null  float64
 75  sensor_46              54986 non-null  float64
 76  sensor_47              54986 non-null  float64
 77  sensor_48              54986 non-null  float64
 78  sensor_49              54986 non-null  float64
 79  sensor_50              54986 non-null  float64
 80  sensor_51              54986 non-null  float64
 81  sensor_52_avg          54986 non-null  float64
 82  sensor_52_max          54986 non-null  float64
 83  sensor_52_min          54986 non-null  float64
 84  sensor_52_std          54986 non-null  float64
 85  sensor_53_avg          54986 non-null  float64
dtypes: float64(81), int64(3), object(2)
memory usage: 36.1+ MB

In [34]:
missing_columns = file_0.columns[ file_0.isna().sum() >= 1]
missing_columns

Index(['sensor_14_avg', 'sensor_22_avg'], dtype='object')

In [35]:
file_0[missing_columns].isna().sum()

sensor_14_avg    1
sensor_22_avg    1
dtype: int64

In [36]:
print(file_0.shape)
print(file_0.dtypes.value_counts())
print(file_0.columns.tolist()[:10])
print(file_0.head(3))

(54986, 86)
float64    81
int64       3
object      2
Name: count, dtype: int64
['time_stamp', 'asset_id', 'id', 'train_test', 'status_type_id', 'sensor_0_avg', 'sensor_1_avg', 'sensor_2_avg', 'wind_speed_3_avg', 'wind_speed_4_avg']
            time_stamp  asset_id  id train_test  status_type_id  sensor_0_avg  \
0  2022-08-04 06:10:00         0   0      train               0          22.0
1  2022-08-04 06:20:00         0   1      train               0          22.0
2  2022-08-04 06:30:00         0   2      train               0          22.0

   sensor_1_avg  sensor_2_avg  wind_speed_3_avg  wind_speed_4_avg  ...  \
0         302.9         129.4               1.7               1.7  ...
1         307.1         133.6               1.7               1.7  ...
2         340.6         167.1               0.9               0.9  ...

   sensor_47  sensor_48  sensor_49  sensor_50  sensor_51  sensor_52_avg  \
0     -496.0        0.0        0.0    -1280.0     -496.0            0.0
1     -490.0        0.0        0.0    -1278.0     -490.0            0.0
2     -490.0        0.0        0.0    -1356.0     -490.0            0.0

   sensor_52_max  sensor_52_min  sensor_52_std  sensor_53_avg
0            0.0            0.0            0.0           26.0
1            0.0            0.0            0.0           25.0
2            0.0            0.0            0.0           25.0

[3 rows x 86 columns]