In [1]:
import pandas as pd 
import numpy as np

In [2]:
benficiary = pd.read_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\raw\Train_Beneficiarydata-1542865627584.csv")
inpatient = pd.read_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\raw\Train_Inpatientdata-1542865627584.csv")
outpatient = pd.read_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\raw\Train_Outpatientdata-1542865627584.csv")
labels = pd.read_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\raw\Train-1542865627584.csv")

In [3]:
benficiary.head()

,BeneID,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,...,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11001,1943-01-01,NaN,1,1,0,39,230,12,12,...,1,1,1,2,1,1,36000,3204,60,70
1,BENE11002,1936-09-01,NaN,2,1,0,39,280,12,12,...,2,2,2,2,2,2,0,0,30,50
2,BENE11003,1936-08-01,NaN,1,1,0,52,590,12,12,...,2,2,1,2,2,2,0,0,90,40
3,BENE11004,1922-07-01,NaN,1,1,0,39,270,12,12,...,2,1,1,1,1,2,0,0,1810,760
4,BENE11005,1935-09-01,NaN,1,1,0,24,680,12,12,...,2,1,2,2,2,2,0,0,1790,1200

In [4]:
inpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,AdmissionDt,...,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6
0,BENE11001,CLM46614,2009-04-12,2009-04-18,PRV55912,26000,PHY390922,NaN,NaN,2009-04-12,...,2724,19889,5849,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BENE11001,CLM66048,2009-08-31,2009-09-02,PRV55907,5000,PHY318495,PHY318495,NaN,2009-08-31,...,NaN,NaN,NaN,NaN,7092.0,NaN,NaN,NaN,NaN,NaN
2,BENE11001,CLM68358,2009-09-17,2009-09-20,PRV56046,5000,PHY372395,NaN,PHY324689,2009-09-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,BENE11011,CLM38412,2009-02-14,2009-02-22,PRV52405,5000,PHY369659,PHY392961,PHY349768,2009-02-14,...,25062,40390,4019,NaN,331.0,NaN,NaN,NaN,NaN,NaN
4,BENE11014,CLM63689,2009-08-13,2009-08-30,PRV56614,10000,PHY379376,PHY398258,NaN,2009-08-13,...,5119,29620,20300,NaN,3893.0,NaN,NaN,NaN,NaN,NaN

In [5]:
outpatient.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,...,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,56409
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,79380
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,71947

In [6]:
labels.head()

   Provider PotentialFraud
0  PRV51001             No
1  PRV51003            Yes
2  PRV51004             No
3  PRV51005            Yes
4  PRV51007             No

In [7]:
labels["PotentialFraud"].value_counts()

PotentialFraud
No     4904
Yes     506
Name: count, dtype: int64

In [8]:
print(inpatient.shape)
print(outpatient.shape)

(40474, 30)
(517737, 27)

In [9]:
pd.set_option("display.max_columns",None)

In [10]:
claims = pd.concat([outpatient, inpatient], axis=0)
claims.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode,AdmissionDt,DischargeDt,DiagnosisGroupCode
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,V5866,V1272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,56409,NaN,NaN,NaN
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,79380,NaN,NaN,NaN
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,30000,72887,4280,7197,V4577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,71947,NaN,NaN,NaN

In [11]:
print(claims.shape)

(558211, 30)

In [12]:
data = claims.merge(benficiary, on="BeneID", how = "left")
data.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,OperatingPhysician,OtherPhysician,ClmDiagnosisCode_1,ClmDiagnosisCode_2,ClmDiagnosisCode_3,ClmDiagnosisCode_4,ClmDiagnosisCode_5,ClmDiagnosisCode_6,ClmDiagnosisCode_7,ClmDiagnosisCode_8,ClmDiagnosisCode_9,ClmDiagnosisCode_10,ClmProcedureCode_1,ClmProcedureCode_2,ClmProcedureCode_3,ClmProcedureCode_4,ClmProcedureCode_5,ClmProcedureCode_6,DeductibleAmtPaid,ClmAdmitDiagnosisCode,AdmissionDt,DischargeDt,DiagnosisGroupCode,DOB,DOD,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,NaN,NaN,78943,V5866,V1272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,56409,NaN,NaN,NaN,1936-09-01,NaN,2,1,0,39,280,12,12,2,2,2,2,2,2,2,2,2,2,2,0,0,30,50
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,NaN,NaN,6115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,79380,NaN,NaN,NaN,1936-08-01,NaN,1,1,0,52,590,12,12,1,2,2,2,2,2,2,1,2,2,2,0,0,90,40
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,NaN,NaN,2723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1936-08-01,NaN,1,1,0,52,590,12,12,1,2,2,2,2,2,2,1,2,2,2,0,0,90,40
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,NaN,NaN,71988,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,1922-07-01,NaN,1,1,0,39,270,12,12,1,1,2,2,2,2,1,1,1,1,2,0,0,1810,760
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,NaN,NaN,82382,30000,72887,4280,7197,V4577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,71947,NaN,NaN,NaN,1922-07-01,NaN,1,1,0,39,270,12,12,1,1,2,2,2,2,1,1,1,1,2,0,0,1810,760

In [13]:
print(data.shape)

(558211, 54)

In [14]:
data.columns

Index(['BeneID', 'ClaimID', 'ClaimStartDt', 'ClaimEndDt', 'Provider',
       'InscClaimAmtReimbursed', 'AttendingPhysician', 'OperatingPhysician',
       'OtherPhysician', 'ClmDiagnosisCode_1', 'ClmDiagnosisCode_2',
       'ClmDiagnosisCode_3', 'ClmDiagnosisCode_4', 'ClmDiagnosisCode_5',
       'ClmDiagnosisCode_6', 'ClmDiagnosisCode_7', 'ClmDiagnosisCode_8',
       'ClmDiagnosisCode_9', 'ClmDiagnosisCode_10', 'ClmProcedureCode_1',
       'ClmProcedureCode_2', 'ClmProcedureCode_3', 'ClmProcedureCode_4',
       'ClmProcedureCode_5', 'ClmProcedureCode_6', 'DeductibleAmtPaid',
       'ClmAdmitDiagnosisCode', 'AdmissionDt', 'DischargeDt',
       'DiagnosisGroupCode', 'DOB', 'DOD', 'Gender', 'Race',
       'RenalDiseaseIndicator', 'State', 'County', 'NoOfMonths_PartACov',
       'NoOfMonths_PartBCov', 'ChronicCond_Alzheimer',
       'ChronicCond_Heartfailure', 'ChronicCond_KidneyDisease',
       'ChronicCond_Cancer', 'ChronicCond_ObstrPulmonary',
       'ChronicCond_Depression', 'ChronicCond_Diabetes',
       'ChronicCond_IschemicHeart', 'ChronicCond_Osteoporasis',
       'ChronicCond_rheumatoidarthritis', 'ChronicCond_stroke',
       'IPAnnualReimbursementAmt', 'IPAnnualDeductibleAmt',
       'OPAnnualReimbursementAmt', 'OPAnnualDeductibleAmt'],
      dtype='object')

In [15]:
data["Provider"].nunique()

5410

In [16]:
pd.set_option("display.max_rows", None)

In [17]:
data.isna().sum()

BeneID                                  0
ClaimID                                 0
ClaimStartDt                            0
ClaimEndDt                              0
Provider                                0
InscClaimAmtReimbursed                  0
AttendingPhysician                   1508
OperatingPhysician                 443764
OtherPhysician                     358475
ClmDiagnosisCode_1                  10453
ClmDiagnosisCode_2                 195606
ClmDiagnosisCode_3                 315156
ClmDiagnosisCode_4                 393675
ClmDiagnosisCode_5                 446287
ClmDiagnosisCode_6                 473819
ClmDiagnosisCode_7                 492034
ClmDiagnosisCode_8                 504767
ClmDiagnosisCode_9                 516396
ClmDiagnosisCode_10                553201
ClmProcedureCode_1                 534901
ClmProcedureCode_2                 552721
ClmProcedureCode_3                 557242
ClmProcedureCode_4                 558093
ClmProcedureCode_5                 558202
ClmProcedureCode_6                 558211
DeductibleAmtPaid                     899
ClmAdmitDiagnosisCode              412312
AdmissionDt                        517737
DischargeDt                        517737
DiagnosisGroupCode                 517737
DOB                                     0
DOD                                554080
Gender                                  0
Race                                    0
RenalDiseaseIndicator                   0
State                                   0
County                                  0
NoOfMonths_PartACov                     0
NoOfMonths_PartBCov                     0
ChronicCond_Alzheimer                   0
ChronicCond_Heartfailure                0
ChronicCond_KidneyDisease               0
ChronicCond_Cancer                      0
ChronicCond_ObstrPulmonary              0
ChronicCond_Depression                  0
ChronicCond_Diabetes                    0
ChronicCond_IschemicHeart               0
ChronicCond_Osteoporasis                0
ChronicCond_rheumatoidarthritis         0
ChronicCond_stroke                      0
IPAnnualReimbursementAmt                0
IPAnnualDeductibleAmt                   0
OPAnnualReimbursementAmt                0
OPAnnualDeductibleAmt                   0
dtype: int64

In [18]:
col = data.columns
size  = len(data)
dec= {}

for name in col :
    missing = data[name].isna().sum()/size * 100
    dec[name] = int(missing)

dec

{'BeneID': 0,
 'ClaimID': 0,
 'ClaimStartDt': 0,
 'ClaimEndDt': 0,
 'Provider': 0,
 'InscClaimAmtReimbursed': 0,
 'AttendingPhysician': 0,
 'OperatingPhysician': 79,
 'OtherPhysician': 64,
 'ClmDiagnosisCode_1': 1,
 'ClmDiagnosisCode_2': 35,
 'ClmDiagnosisCode_3': 56,
 'ClmDiagnosisCode_4': 70,
 'ClmDiagnosisCode_5': 79,
 'ClmDiagnosisCode_6': 84,
 'ClmDiagnosisCode_7': 88,
 'ClmDiagnosisCode_8': 90,
 'ClmDiagnosisCode_9': 92,
 'ClmDiagnosisCode_10': 99,
 'ClmProcedureCode_1': 95,
 'ClmProcedureCode_2': 99,
 'ClmProcedureCode_3': 99,
 'ClmProcedureCode_4': 99,
 'ClmProcedureCode_5': 99,
 'ClmProcedureCode_6': 100,
 'DeductibleAmtPaid': 0,
 'ClmAdmitDiagnosisCode': 73,
 'AdmissionDt': 92,
 'DischargeDt': 92,
 'DiagnosisGroupCode': 92,
 'DOB': 0,
 'DOD': 99,
 'Gender': 0,
 'Race': 0,
 'RenalDiseaseIndicator': 0,
 'State': 0,
 'County': 0,
 'NoOfMonths_PartACov': 0,
 'NoOfMonths_PartBCov': 0,
 'ChronicCond_Alzheimer': 0,
 'ChronicCond_Heartfailure': 0,
 'ChronicCond_KidneyDisease': 0,
 'ChronicCond_Cancer': 0,
 'ChronicCond_ObstrPulmonary': 0,
 'ChronicCond_Depression': 0,
 'ChronicCond_Diabetes': 0,
 'ChronicCond_IschemicHeart': 0,
 'ChronicCond_Osteoporasis': 0,
 'ChronicCond_rheumatoidarthritis': 0,
 'ChronicCond_stroke': 0,
 'IPAnnualReimbursementAmt': 0,
 'IPAnnualDeductibleAmt': 0,
 'OPAnnualReimbursementAmt': 0,
 'OPAnnualDeductibleAmt': 0}

In [19]:
result = []

for key, value in dec.items():
    if value < 15:
        result.append(key)
result

['BeneID',
 'ClaimID',
 'ClaimStartDt',
 'ClaimEndDt',
 'Provider',
 'InscClaimAmtReimbursed',
 'AttendingPhysician',
 'ClmDiagnosisCode_1',
 'DeductibleAmtPaid',
 'DOB',
 'Gender',
 'Race',
 'RenalDiseaseIndicator',
 'State',
 'County',
 'NoOfMonths_PartACov',
 'NoOfMonths_PartBCov',
 'ChronicCond_Alzheimer',
 'ChronicCond_Heartfailure',
 'ChronicCond_KidneyDisease',
 'ChronicCond_Cancer',
 'ChronicCond_ObstrPulmonary',
 'ChronicCond_Depression',
 'ChronicCond_Diabetes',
 'ChronicCond_IschemicHeart',
 'ChronicCond_Osteoporasis',
 'ChronicCond_rheumatoidarthritis',
 'ChronicCond_stroke',
 'IPAnnualReimbursementAmt',
 'IPAnnualDeductibleAmt',
 'OPAnnualReimbursementAmt',
 'OPAnnualDeductibleAmt']

In [29]:
new_df = data[result[:]]

In [30]:
new_df.head()

,BeneID,ClaimID,ClaimStartDt,ClaimEndDt,Provider,InscClaimAmtReimbursed,AttendingPhysician,ClmDiagnosisCode_1,DeductibleAmtPaid,DOB,Gender,Race,RenalDiseaseIndicator,State,County,NoOfMonths_PartACov,NoOfMonths_PartBCov,ChronicCond_Alzheimer,ChronicCond_Heartfailure,ChronicCond_KidneyDisease,ChronicCond_Cancer,ChronicCond_ObstrPulmonary,ChronicCond_Depression,ChronicCond_Diabetes,ChronicCond_IschemicHeart,ChronicCond_Osteoporasis,ChronicCond_rheumatoidarthritis,ChronicCond_stroke,IPAnnualReimbursementAmt,IPAnnualDeductibleAmt,OPAnnualReimbursementAmt,OPAnnualDeductibleAmt
0,BENE11002,CLM624349,2009-10-11,2009-10-11,PRV56011,30,PHY326117,78943,0.0,1936-09-01,2,1,0,39,280,12,12,2,2,2,2,2,2,2,2,2,2,2,0,0,30,50
1,BENE11003,CLM189947,2009-02-12,2009-02-12,PRV57610,80,PHY362868,6115,0.0,1936-08-01,1,1,0,52,590,12,12,1,2,2,2,2,2,2,1,2,2,2,0,0,90,40
2,BENE11003,CLM438021,2009-06-27,2009-06-27,PRV57595,10,PHY328821,2723,0.0,1936-08-01,1,1,0,52,590,12,12,1,2,2,2,2,2,2,1,2,2,2,0,0,90,40
3,BENE11004,CLM121801,2009-01-06,2009-01-06,PRV56011,40,PHY334319,71988,0.0,1922-07-01,1,1,0,39,270,12,12,1,1,2,2,2,2,1,1,1,1,2,0,0,1810,760
4,BENE11004,CLM150998,2009-01-22,2009-01-22,PRV56011,200,PHY403831,82382,0.0,1922-07-01,1,1,0,39,270,12,12,1,1,2,2,2,2,1,1,1,1,2,0,0,1810,760

In [36]:
provider_features = new_df.groupby("Provider").agg({
    "ClaimID" : "count",
    'InscClaimAmtReimbursed': ['sum', 'mean', 'std'],
    'BeneID': 'nunique',
    'AttendingPhysician': 'nunique',
    "IPAnnualReimbursementAmt" : ["sum", "mean", "std"],
    "OPAnnualReimbursementAmt" : ["sum", "mean", "std"],
    "IPAnnualDeductibleAmt" : ["sum", "mean", "std"],
    "OPAnnualDeductibleAmt" : ["sum", "mean", "std"],
}).reset_index()

provider_features.columns = ["Provider","ClaimId_count", "ICR_sum","ICR_mean","ICR_std","Ben_nunique","AP_nunique","IPAR_sum","IPAR_mean","IPAR_std",
                             "OPAR_sum","OPAR_mean","OPAR_std","IPDA_sum","IPDA_mean","IPDA_std","OPDA_sum","OPDA_mean","OPDA_std"]
provider_features.head(20)

,Provider,ClaimId_count,ICR_sum,ICR_mean,ICR_std,Ben_nunique,AP_nunique,IPAR_sum,IPAR_mean,IPAR_std,OPAR_sum,OPAR_mean,OPAR_std,IPDA_sum,IPDA_mean,IPDA_std,OPDA_sum,OPDA_mean,OPDA_std
0,PRV51001,25,104640,4185.600000,10796.091144,24,14,440150,17606.000000,38895.477458,65380,2615.200000,2974.176525,22428,897.120000,1332.505670,11598,463.920000,635.782321
1,PRV51003,132,605670,4588.409091,7309.794729,117,44,999000,7568.181818,10040.975578,353520,2678.181818,5190.714819,122948,931.424242,1059.574926,97300,737.121212,1517.084151
2,PRV51004,149,52170,350.134228,689.963754,138,38,648430,4351.879195,9889.562978,327040,2194.899329,3198.010914,64808,434.953020,945.236867,92790,622.751678,873.191458
3,PRV51005,1165,280910,241.124464,491.556392,495,6,4221950,3623.991416,9688.526566,2457840,2109.733906,3960.211085,441724,379.162232,751.597235,741323,636.328755,845.696041
4,PRV51007,72,33710,468.194444,1433.769116,58,10,219600,3050.000000,5682.560175,124540,1729.722222,1623.875535,32040,445.000000,796.600594,33820,469.722222,518.885513
5,PRV51008,43,35630,828.604651,3224.765463,36,10,283460,6592.093023,15111.833988,110530,2570.465116,3546.637545,26700,620.930233,995.142808,26490,616.046512,741.067889
6,PRV51011,58,16630,286.724138,701.047807,53,28,256060,4414.827586,7314.270656,81160,1399.310345,1326.395805,39108,674.275862,1280.311390,21270,366.724138,275.753436
7,PRV51012,48,16890,351.875000,707.893658,31,14,332900,6935.416667,10616.797000,182110,3793.958333,8052.692094,40316,839.916667,1235.219471,35290,735.208333,1309.427339
8,PRV51013,46,14880,323.478261,471.622341,44,9,167240,3635.652174,7643.826747,148420,3226.521739,5385.073699,27292,593.304348,1616.480249,42080,914.782609,1523.187796
9,PRV51014,30,10480,349.333333,822.984197,25,7,83590,2786.333333,4484.440905,52270,1742.333333,1440.257839,12816,427.200000,663.714438,19480,649.333333,645.797734
10,PRV51015,8,700,87.500000,74.017372,7,3,9490,1186.250000,2232.314222,11560,1445.000000,1020.993914,2136,267.000000,494.387933,2110,263.750000,188.599159
11,PRV51016,6,170,28.333333,37.638633,6,3,0,0.000000,0.000000,5270,878.333333,1343.270884,0,0.000000,0.000000,1770,295.000000,231.062762
12,PRV51017,515,142720,277.126214,570.181804,420,113,1711200,3322.718447,7568.380388,1221060,2370.990291,4365.843948,198512,385.460194,736.082244,354990,689.300971,1135.735375
13,PRV51021,257,348830,1357.315175,4462.486891,208,69,1255950,4886.964981,10815.008963,692640,2695.097276,4658.966834,149776,582.785992,999.295199,197902,770.046693,1203.205899
14,PRV51023,36,65610,1822.500000,3084.698063,35,14,191530,5320.277778,8000.246598,89120,2475.555556,4269.826657,30364,843.444444,1189.076435,27700,769.444444,1354.589963
15,PRV51024,39,64050,1642.307692,3334.489199,38,13,178100,4566.666667,6952.056997,76950,1973.076923,3646.168973,24564,629.846154,907.484132,26080,668.717949,991.068481
16,PRV51025,87,118350,1360.344828,3052.031900,76,35,419650,4823.563218,8696.344190,199140,2288.965517,3361.467715,48060,552.413793,828.263756,54060,621.379310,1005.927979
17,PRV51026,76,19840,261.052632,668.783132,56,29,301800,3971.052632,9266.044331,137680,1811.578947,1612.617791,35040,461.052632,900.713878,51710,680.394737,696.023833
18,PRV51027,53,29840,563.018868,1044.044622,44,10,330250,6231.132075,10971.637852,188920,3564.528302,6245.201101,37380,705.283019,1146.133238,50200,947.169811,1841.851470
19,PRV51029,93,30660,329.677419,618.311958,79,38,357960,3849.032258,10114.278120,154470,1660.967742,1669.563901,38040,409.032258,935.653207,45860,493.118280,470.520014

In [37]:
provider_features.shape

(5410, 19)

In [39]:
final_data = provider_features.merge(labels, on = "Provider")
final_data.head()

,Provider,ClaimId_count,ICR_sum,ICR_mean,ICR_std,Ben_nunique,AP_nunique,IPAR_sum,IPAR_mean,IPAR_std,OPAR_sum,OPAR_mean,OPAR_std,IPDA_sum,IPDA_mean,IPDA_std,OPDA_sum,OPDA_mean,OPDA_std,PotentialFraud
0,PRV51001,25,104640,4185.600000,10796.091144,24,14,440150,17606.000000,38895.477458,65380,2615.200000,2974.176525,22428,897.120000,1332.505670,11598,463.920000,635.782321,No
1,PRV51003,132,605670,4588.409091,7309.794729,117,44,999000,7568.181818,10040.975578,353520,2678.181818,5190.714819,122948,931.424242,1059.574926,97300,737.121212,1517.084151,Yes
2,PRV51004,149,52170,350.134228,689.963754,138,38,648430,4351.879195,9889.562978,327040,2194.899329,3198.010914,64808,434.953020,945.236867,92790,622.751678,873.191458,No
3,PRV51005,1165,280910,241.124464,491.556392,495,6,4221950,3623.991416,9688.526566,2457840,2109.733906,3960.211085,441724,379.162232,751.597235,741323,636.328755,845.696041,Yes
4,PRV51007,72,33710,468.194444,1433.769116,58,10,219600,3050.000000,5682.560175,124540,1729.722222,1623.875535,32040,445.000000,796.600594,33820,469.722222,518.885513,No

In [40]:
final_data.to_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\processed_data\final_data.csv")

In [41]:
final_data.columns

Index(['Provider', 'ClaimId_count', 'ICR_sum', 'ICR_mean', 'ICR_std',
       'Ben_nunique', 'AP_nunique', 'IPAR_sum', 'IPAR_mean', 'IPAR_std',
       'OPAR_sum', 'OPAR_mean', 'OPAR_std', 'IPDA_sum', 'IPDA_mean',
       'IPDA_std', 'OPDA_sum', 'OPDA_mean', 'OPDA_std', 'PotentialFraud'],
      dtype='object')