In [2]:
import pandas as pd
import numpy as np 
import plotly.graph_objects as go 
import plotly.express as px

In [3]:
pd.set_option("display.max_columns",None)

In [39]:
df = pd.read_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\processed_data\final_data.csv")
df.head()

,Unnamed: 0,Provider,ClaimId_count,ICR_sum,ICR_mean,ICR_std,Ben_nunique,AP_nunique,IPAR_sum,IPAR_mean,IPAR_std,OPAR_sum,OPAR_mean,OPAR_std,IPDA_sum,IPDA_mean,IPDA_std,OPDA_sum,OPDA_mean,OPDA_std,PotentialFraud
0,0,PRV51001,25,104640,4185.600000,10796.091144,24,14,440150,17606.000000,38895.477458,65380,2615.200000,2974.176525,22428,897.120000,1332.505670,11598,463.920000,635.782321,No
1,1,PRV51003,132,605670,4588.409091,7309.794729,117,44,999000,7568.181818,10040.975578,353520,2678.181818,5190.714819,122948,931.424242,1059.574926,97300,737.121212,1517.084151,Yes
2,2,PRV51004,149,52170,350.134228,689.963754,138,38,648430,4351.879195,9889.562978,327040,2194.899329,3198.010914,64808,434.953020,945.236867,92790,622.751678,873.191458,No
3,3,PRV51005,1165,280910,241.124464,491.556392,495,6,4221950,3623.991416,9688.526566,2457840,2109.733906,3960.211085,441724,379.162232,751.597235,741323,636.328755,845.696041,Yes
4,4,PRV51007,72,33710,468.194444,1433.769116,58,10,219600,3050.000000,5682.560175,124540,1729.722222,1623.875535,32040,445.000000,796.600594,33820,469.722222,518.885513,No

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      5410 non-null   int64
 1   Provider        5410 non-null   object
 2   ClaimId_count   5410 non-null   int64
 3   ICR_sum         5410 non-null   int64
 4   ICR_mean        5410 non-null   float64
 5   ICR_std         5170 non-null   float64
 6   Ben_nunique     5410 non-null   int64
 7   AP_nunique      5410 non-null   int64
 8   IPAR_sum        5410 non-null   int64
 9   IPAR_mean       5410 non-null   float64
 10  IPAR_std        5170 non-null   float64
 11  OPAR_sum        5410 non-null   int64
 12  OPAR_mean       5410 non-null   float64
 13  OPAR_std        5170 non-null   float64
 14  IPDA_sum        5410 non-null   int64
 15  IPDA_mean       5410 non-null   float64
 16  IPDA_std        5170 non-null   float64
 17  OPDA_sum        5410 non-null   int64
 18  OPDA_mean       5410 non-null   float64
 19  OPDA_std        5170 non-null   float64
 20  PotentialFraud  5410 non-null   object
dtypes: float64(10), int64(9), object(2)
memory usage: 887.7+ KB

In [41]:
df.describe()

,Unnamed: 0,ClaimId_count,ICR_sum,ICR_mean,ICR_std,Ben_nunique,AP_nunique,IPAR_sum,IPAR_mean,IPAR_std,OPAR_sum,OPAR_mean,OPAR_std,IPDA_sum,IPDA_mean,IPDA_std,OPDA_sum,OPDA_mean,OPDA_std
count,5410.000000,5410.000000,5.410000e+03,5410.000000,5170.000000,5410.000000,5410.000000,5.410000e+03,5410.000000,5170.000000,5.410000e+03,5410.000000,5170.000000,5.410000e+03,5410.000000,5170.000000,5.410000e+03,5410.000000,5170.000000
mean,2704.500000,103.181331,1.028730e+05,1740.679369,2536.575975,67.153420,16.248614,5.394291e+05,6166.692586,10218.354703,2.350703e+05,2199.335651,3059.174105,5.868508e+04,666.980865,958.534810,6.703678e+04,629.095618,817.872075
std,1561.876809,272.456989,2.687367e+05,3484.473124,3694.559177,142.748729,28.861828,1.307558e+06,6203.422910,6412.966395,6.339728e+05,1301.128843,2209.012817,1.437551e+05,623.108956,757.996867,1.812672e+05,344.104149,515.723845
min,0.000000,1.000000,0.000000e+00,0.000000,0.000000,1.000000,1.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,1352.250000,10.000000,4.460000e+03,232.394593,445.314551,8.000000,2.000000,4.405750e+04,2902.238095,6244.112694,1.818250e+04,1547.500000,1552.423573,5.340000e+03,356.000000,622.764327,5.500000e+03,459.656897,468.083449
50%,2704.500000,31.000000,1.980500e+04,356.085106,714.121955,25.000000,6.000000,1.624000e+05,4729.047927,9698.727032,6.566000e+04,2044.355263,2577.022644,1.815600e+04,527.580008,852.609368,1.908000e+04,592.510504,720.214927
75%,4056.750000,87.000000,8.556500e+04,1490.154301,3610.717613,65.000000,19.000000,4.745750e+05,7336.173195,13124.267783,1.997150e+05,2557.354123,4066.098575,5.233200e+04,801.000000,1099.032164,5.693000e+04,726.026854,1050.208479
max,5409.000000,8240.000000,5.996050e+06,57000.000000,50204.581464,2857.000000,643.000000,3.397843e+07,103000.000000,78771.695424,1.909821e+07,22853.333333,24097.435237,3.924816e+06,12068.000000,17066.729271,5.456830e+06,6070.000000,5911.412691

In [42]:
df["Provider"].nunique()

5410

In [43]:
class_balance = df["PotentialFraud"].value_counts().reset_index()
class_balance

  PotentialFraud  count
0             No   4904
1            Yes    506

In [44]:
fig = go.Figure()

fig.add_trace(
    go.Bar(
        x = class_balance["PotentialFraud"],
        y = class_balance["count"],
        marker= dict(color = "yellow", line = dict(width = 1, color = "black")),
        text = class_balance["PotentialFraud"]
    )
)
fig.update_layout(
    title = "Distribution of Potential Fraud Cases",
    xaxis_title = "Count",
    yaxis_title = "Potential Fraud",
    template = "plotly_white" 
)
fig.show()

In [45]:
fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x = df["ClaimId_count"],
        marker= dict(color = "blue", line = dict(width = 1, color = "black")),
        nbinsx=15
    )
)
# fig.update_xaxes(type = "log")
fig.update_layout(
    title = "Distribution of Claim ID Counts",
    xaxis_title = "Claim ID Count",
    yaxis_title = "Frequency",
    template = "plotly_white"
)

fig.show()

In [46]:


fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x = df["ICR_sum"],
        marker= dict(color = "pink", line = dict(width = 1, color = "black")),
        nbinsx=15
    )
)
# fig.update_xaxes(type="log")  
fig.update_layout(
    title = "Distribution of ICR_sum",
    xaxis_title = "ICR_sum",
    yaxis_title = "Frequency",
    template = "plotly_white"
)

fig.show()

In [48]:
df["ICR_sum_log"] = np.log(df["ICR_sum"])

c:\Users\RITHIK KUMAR\.conda\envs\p11venv\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning:

divide by zero encountered in log

In [49]:


fig = go.Figure()

fig.add_trace(
    go.Histogram(
        x = df["ICR_sum_log"],
        marker= dict(color = "pink", line = dict(width = 1, color = "black")),
        nbinsx=15
    )
)
# fig.update_xaxes(type="log")  
fig.update_layout(
    title = "Distribution of ICR_sum_log",
    xaxis_title = "ICR_sum_log",
    yaxis_title = "Frequency",
    template = "plotly_white"
)

fig.show()

In [14]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x = df["ClaimId_count"],
        y = df["ICR_sum"],
        mode = 'markers',  
        marker = dict(
            size = 5,
            color = 'blue',
            opacity = 0.6,
            line = dict(width = 1, color = 'black')
        )
    )
)

fig.update_layout(
    title = "Relationship between Claim Count and ICR Sum",
    xaxis_title = "Claim ID Count",
    yaxis_title = "ICR Sum",
    template = "plotly_white",
    hovermode = 'closest'
)

fig.show()

In [15]:
df["ClaimId_count_log"] = np.log(df["ClaimId_count"])

In [16]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x = df["ClaimId_count_log"],
        y = df["ICR_sum_log"],
        mode = 'markers',  
        marker = dict(
            size = 5,
            color = 'orange',
            opacity = 0.6,
            line = dict(width = 1, color = 'black')
        )
    )
)

fig.update_layout(
    title = "Relationship between Claim Count and ICR Sum (Log Scale)",
    xaxis_title = "log(Claim ID Count)",
    yaxis_title = "log(ICR Sum)",
    template = "plotly_white",
    hovermode = 'closest'
)

fig.show()

In [17]:
X = df[["ClaimId_count", "ICR_sum"]].copy()
import numpy as np

X["log_claims"] = np.log1p(X["ClaimId_count"])
X["log_icr"] = np.log1p(X["ICR_sum"])

In [18]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()
lr.fit(X[["log_claims"]], X["log_icr"])

LinearRegression()

In [19]:
X["expected_log_icr"] = lr.predict(X[["log_claims"]])
X["residual"] = X["log_icr"] - X["expected_log_icr"]

In [20]:
X["anomaly_score"] = X["residual"].clip(lower=0)

In [21]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x = X["expected_log_icr"],
        y = X["residual"],
        mode = 'markers',  
        marker = dict(
            size = 5,
            opacity = 0.6,
            color = X["anomaly_score"],
            colorscale = 'Viridis',
            colorbar = dict(title = "Anomaly Score"),
            line = dict(width = 1, color = 'black')
        ),
        
    )
)

fig.update_layout(
    title = "Relationship between expected_log_icr and residual",
    xaxis_title = "expected_log_icr",
    yaxis_title = "residual",
    template = "plotly_white",
    hovermode = 'closest'
)

fig.show()

In [22]:
result = (
    df[["Provider", "PotentialFraud"]]
    .join(X[["anomaly_score", "residual"]])
    .sort_values("anomaly_score", ascending=False)
)

In [23]:
result[result["PotentialFraud"] == "Yes"]

      Provider PotentialFraud  anomaly_score  residual
645   PRV51805            Yes       3.862853  3.862853
2646  PRV54297            Yes       3.832704  3.832704
1156  PRV52445            Yes       3.808423  3.808423
4726  PRV56918            Yes       3.802465  3.802465
3306  PRV55147            Yes       3.723257  3.723257
...        ...            ...            ...       ...
853   PRV52064            Yes       0.000000 -1.009514
5329  PRV57672            Yes       0.000000 -1.034865
849   PRV52059            Yes       0.000000 -0.809442
25    PRV51037            Yes       0.000000 -0.048786
3     PRV51005            Yes       0.000000 -1.347969

[506 rows x 4 columns]

In [24]:
fig = go.Figure()


fig.add_trace(
    go.Box(
        x = result["PotentialFraud"],
        y = result["anomaly_score"],
        marker = dict(color ="red", line = dict(width = 1,color = "black")),
        boxpoints = 'outliers'
    )
)
fig.update_layout(
    title = "Distribution of Potential Fraud on Anamoaly Score",
    xaxis_title = "Potential Fraud",
    yaxis_title = "Anomaly Score"
)

fig.show()

In [30]:
df = pd.read_csv(r"C:\potfolio\Health_care_provider_fraud_detection\data\processed_data\final_data.csv")
df = df[["Provider","PotentialFraud"]]
result["Provider"] = result["Provider"].astype(str)
df["Provider"] = df["Provider"].astype(str)

# Use merge
data = result.merge(df, on="Provider", how="left")
data.head()

   Provider PotentialFraud_x  anomaly_score  residual PotentialFraud_y
0  PRV52537               No       4.512728  4.512728               No
1  PRV57399               No       4.512728  4.512728               No
2  PRV57080               No       4.512728  4.512728               No
3  PRV53033               No       4.312456  4.312456               No
4  PRV52696               No       4.222504  4.222504               No

In [37]:
data[data["PotentialFraud_x"]=="Yes"]["PotentialFraud_x"].count()

np.int64(506)

In [36]:
data[data["PotentialFraud_y"]=="Yes"]["PotentialFraud_y"].count()

np.int64(506)

In [35]:
(data["PotentialFraud_x"] == data["PotentialFraud_y"]).sum()

np.int64(5410)