In [1]:
import pandas as pd 
import numpy as np 
from  statsmodels.stats  import stattools
import plotly.graph_objects as go 
import plotly.express as px

## LR Assumptions
* The target and the predictor relationship is linear. 
* Residuals are independent of each other.
* Predictors are not highly correlated with each other.

In [2]:
house_price = pd.read_csv(r"C:\potfolio\Advance_house_price_prediction\data\raw\train.csv")
house_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [3]:
missing_list = {}
length = len(house_price)
for col in house_price.columns:
    missing = ((house_price[col].isna().sum())/length)*100
    missing_list[col] = round(missing,2)
missing_list

{'Id': 0.0,
 'MSSubClass': 0.0,
 'MSZoning': 0.0,
 'LotFrontage': 17.74,
 'LotArea': 0.0,
 'Street': 0.0,
 'Alley': 93.77,
 'LotShape': 0.0,
 'LandContour': 0.0,
 'Utilities': 0.0,
 'LotConfig': 0.0,
 'LandSlope': 0.0,
 'Neighborhood': 0.0,
 'Condition1': 0.0,
 'Condition2': 0.0,
 'BldgType': 0.0,
 'HouseStyle': 0.0,
 'OverallQual': 0.0,
 'OverallCond': 0.0,
 'YearBuilt': 0.0,
 'YearRemodAdd': 0.0,
 'RoofStyle': 0.0,
 'RoofMatl': 0.0,
 'Exterior1st': 0.0,
 'Exterior2nd': 0.0,
 'MasVnrType': 59.73,
 'MasVnrArea': 0.55,
 'ExterQual': 0.0,
 'ExterCond': 0.0,
 'Foundation': 0.0,
 'BsmtQual': 2.53,
 'BsmtCond': 2.53,
 'BsmtExposure': 2.6,
 'BsmtFinType1': 2.53,
 'BsmtFinSF1': 0.0,
 'BsmtFinType2': 2.6,
 'BsmtFinSF2': 0.0,
 'BsmtUnfSF': 0.0,
 'TotalBsmtSF': 0.0,
 'Heating': 0.0,
 'HeatingQC': 0.0,
 'CentralAir': 0.0,
 'Electrical': 0.07,
 '1stFlrSF': 0.0,
 '2ndFlrSF': 0.0,
 'LowQualFinSF': 0.0,
 'GrLivArea': 0.0,
 'BsmtFullBath': 0.0,
 'BsmtHalfBath': 0.0,
 'FullBath': 0.0,
 'HalfBath': 0.0,
 'BedroomAbvGr': 0.0,
 'KitchenAbvGr': 0.0,
 'KitchenQual': 0.0,
 'TotRmsAbvGrd': 0.0,
 'Functional': 0.0,
 'Fireplaces': 0.0,
 'FireplaceQu': 47.26,
 'GarageType': 5.55,
 'GarageYrBlt': 5.55,
 'GarageFinish': 5.55,
 'GarageCars': 0.0,
 'GarageArea': 0.0,
 'GarageQual': 5.55,
 'GarageCond': 5.55,
 'PavedDrive': 0.0,
 'WoodDeckSF': 0.0,
 'OpenPorchSF': 0.0,
 'EnclosedPorch': 0.0,
 '3SsnPorch': 0.0,
 'ScreenPorch': 0.0,
 'PoolArea': 0.0,
 'PoolQC': 99.52,
 'Fence': 80.75,
 'MiscFeature': 96.3,
 'MiscVal': 0.0,
 'MoSold': 0.0,
 'YrSold': 0.0,
 'SaleType': 0.0,
 'SaleCondition': 0.0,
 'SalePrice': 0.0}

In [4]:
selected_columns = []
resonable_missing = []
for col_name, missing in missing_list.items():
    if missing > 0 and missing < 10:
        resonable_missing.append(col_name)
        continue
    if  missing < 15:
        selected_columns.append(col_name)
print(len(missing_list))
print(len(selected_columns))
resonable_missing

81
62

['MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [5]:
df = house_price[selected_columns+resonable_missing]
df.shape

(1460, 74)

In [6]:
def impute_missing(col):
    return house_price[col].mean()

In [7]:
for col in resonable_missing:
    print(df[col].dtype)

float64
object
object
object
object
object
object
object
float64
object
object
object

In [8]:
for col in resonable_missing:
    type = df[col].dtype
    if type == "float64" :
        fill = df[col].mean()
        df[col] = df[col].fillna(fill)
    else:
        df[col] = df[col].fillna("unknown")
df.head()

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2237177990.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna(fill)
C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2237177990.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].fillna("unknown")

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,TA,No,GLQ,Unf,SBrkr,Attchd,2003.0,RFn,TA,TA
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,TA,Gd,ALQ,Unf,SBrkr,Attchd,1976.0,RFn,TA,TA
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,TA,Mn,GLQ,Unf,SBrkr,Attchd,2001.0,RFn,TA,TA
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,Gd,No,ALQ,Unf,SBrkr,Detchd,1998.0,Unf,TA,TA
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,TA,Av,GLQ,Unf,SBrkr,Attchd,2000.0,RFn,TA,TA

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 74 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   LotShape       1460 non-null   object
 6   LandContour    1460 non-null   object
 7   Utilities      1460 non-null   object
 8   LotConfig      1460 non-null   object
 9   LandSlope      1460 non-null   object
 10  Neighborhood   1460 non-null   object
 11  Condition1     1460 non-null   object
 12  Condition2     1460 non-null   object
 13  BldgType       1460 non-null   object
 14  HouseStyle     1460 non-null   object
 15  OverallQual    1460 non-null   int64
 16  OverallCond    1460 non-null   int64
 17  YearBuilt      1460 non-null   int64
 18  YearRemodAdd   1460 non-null   int64
 19  RoofStyle      1460 non-null   object
 20  RoofMatl       1460 non-null   object
 21  Exterior1st    1460 non-null   object
 22  Exterior2nd    1460 non-null   object
 23  ExterQual      1460 non-null   object
 24  ExterCond      1460 non-null   object
 25  Foundation     1460 non-null   object
 26  BsmtFinSF1     1460 non-null   int64
 27  BsmtFinSF2     1460 non-null   int64
 28  BsmtUnfSF      1460 non-null   int64
 29  TotalBsmtSF    1460 non-null   int64
 30  Heating        1460 non-null   object
 31  HeatingQC      1460 non-null   object
 32  CentralAir     1460 non-null   object
 33  1stFlrSF       1460 non-null   int64
 34  2ndFlrSF       1460 non-null   int64
 35  LowQualFinSF   1460 non-null   int64
 36  GrLivArea      1460 non-null   int64
 37  BsmtFullBath   1460 non-null   int64
 38  BsmtHalfBath   1460 non-null   int64
 39  FullBath       1460 non-null   int64
 40  HalfBath       1460 non-null   int64
 41  BedroomAbvGr   1460 non-null   int64
 42  KitchenAbvGr   1460 non-null   int64
 43  KitchenQual    1460 non-null   object
 44  TotRmsAbvGrd   1460 non-null   int64
 45  Functional     1460 non-null   object
 46  Fireplaces     1460 non-null   int64
 47  GarageCars     1460 non-null   int64
 48  GarageArea     1460 non-null   int64
 49  PavedDrive     1460 non-null   object
 50  WoodDeckSF     1460 non-null   int64
 51  OpenPorchSF    1460 non-null   int64
 52  EnclosedPorch  1460 non-null   int64
 53  3SsnPorch      1460 non-null   int64
 54  ScreenPorch    1460 non-null   int64
 55  PoolArea       1460 non-null   int64
 56  MiscVal        1460 non-null   int64
 57  MoSold         1460 non-null   int64
 58  YrSold         1460 non-null   int64
 59  SaleType       1460 non-null   object
 60  SaleCondition  1460 non-null   object
 61  SalePrice      1460 non-null   int64
 62  MasVnrArea     1460 non-null   float64
 63  BsmtQual       1460 non-null   object
 64  BsmtCond       1460 non-null   object
 65  BsmtExposure   1460 non-null   object
 66  BsmtFinType1   1460 non-null   object
 67  BsmtFinType2   1460 non-null   object
 68  Electrical     1460 non-null   object
 69  GarageType     1460 non-null   object
 70  GarageYrBlt    1460 non-null   float64
 71  GarageFinish   1460 non-null   object
 72  GarageQual     1460 non-null   object
 73  GarageCond     1460 non-null   object
dtypes: float64(2), int64(35), object(37)
memory usage: 844.2+ KB

In [10]:
df.isna().sum()

Id              0
MSSubClass      0
MSZoning        0
LotArea         0
Street          0
               ..
GarageType      0
GarageYrBlt     0
GarageFinish    0
GarageQual      0
GarageCond      0
Length: 74, dtype: int64

In [11]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'Street', 'LotShape',
       'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl',
       'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'GarageCars', 'GarageArea', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice', 'MasVnrArea', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical',
       'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageQual',
       'GarageCond'],
      dtype='object')

In [12]:
numerical_features = df.select_dtypes(include=["float64","int64"]).columns
num_df = df[numerical_features]
corr = num_df.corr()

fig = go.Figure()

fig.add_trace(
    go.Heatmap(
        z = corr.values,
        y = corr.columns,
        x = corr.columns,
        colorscale="RdBu",
        zmin=-1,
        zmax=1
    )
)
fig.update_layout(
    title="Correlation Heatmap",
    xaxis_title="Features",
    yaxis_title="Features",
    height=800
)

fig.show()

In [13]:
# import seaborn as sns
# import matplotlib.pyplot  as plt

# sns.pairplot(
#     df[numerical_features],
#     hue="SalePrice"
# )
# plt.show()

In [14]:
skewness = {} 
for col in numerical_features:
    skew = df[col].skew()
    skewness[col] = [skew]
    kurtosis = df[col].kurtosis()
    skewness[col].append(kurtosis)
skewness

{'Id': [0.0, -1.1999999999999997],
 'MSSubClass': [1.4076567471495591, 1.5801879649863309],
 'LotArea': [12.207687851233496, 203.24327101886033],
 'OverallQual': [0.2169439277628693, 0.09629277835615113],
 'OverallCond': [0.6930674724842182, 1.1064134613731684],
 'YearBuilt': [-0.613461172488183, -0.43955194159361977],
 'YearRemodAdd': [-0.5035620027004709, -1.2722451924732956],
 'BsmtFinSF1': [1.685503071910789, 11.118236291964712],
 'BsmtFinSF2': [4.255261108933303, 20.11333754558646],
 'BsmtUnfSF': [0.9202684528039037, 0.47499398780908475],
 'TotalBsmtSF': [1.5242545490627664, 13.250483281984796],
 '1stFlrSF': [1.3767566220336365, 5.74584148244079],
 '2ndFlrSF': [0.8130298163023265, -0.5534635576075795],
 'LowQualFinSF': [9.011341288465387, 83.2348166744174],
 'GrLivArea': [1.3665603560164552, 4.895120580693174],
 'BsmtFullBath': [0.596066609663168, -0.8390982654634271],
 'BsmtHalfBath': [4.103402697955168, 16.396641945350446],
 'FullBath': [0.036561558402727165, -0.8570428212743262],
 'HalfBath': [0.675897448233722, -1.0769272841476227],
 'BedroomAbvGr': [0.21179009627507137, 2.230874582191236],
 'KitchenAbvGr': [4.488396777072859, 21.532403840138784],
 'TotRmsAbvGrd': [0.6763408364355531, 0.8807615657189474],
 'Fireplaces': [0.6495651830548841, -0.21723720752814657],
 'GarageCars': [-0.3425489297486655, 0.22099776396532844],
 'GarageArea': [0.17998090674623907, 0.9170672022708684],
 'WoodDeckSF': [1.5413757571931312, 2.992950924703908],
 'OpenPorchSF': [2.3643417403694404, 8.490335805910506],
 'EnclosedPorch': [3.08987190371177, 10.430765944030428],
 '3SsnPorch': [10.304342032693112, 123.66237944970538],
 'ScreenPorch': [4.122213743143115, 18.43906784486968],
 'PoolArea': [14.828373640750588, 223.2684989181717],
 'MiscVal': [24.476794188821916, 701.0033422801193],
 'MoSold': [0.21205298505146022, -0.40410934153702316],
 'YrSold': [0.09626851386568028, -1.1906005711948109],
 'SalePrice': [1.8828757597682129, 6.536281860064529],
 'MasVnrArea': [2.676411784729959, 10.15431640146072],
 'GarageYrBlt': [-0.6681748227563908, -0.26650289988703246]}

In [15]:
high_skewness = []
for key, value in skewness.items():
    if abs(value[0]) > 1:
        high_skewness.append(key)
high_skewness

['MSSubClass',
 'LotArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'TotalBsmtSF',
 '1stFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtHalfBath',
 'KitchenAbvGr',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'SalePrice',
 'MasVnrArea']

In [16]:
def plot_frequency(col):
    fig = go.Figure()
    fig.add_trace(
        go.Histogram(
            x=df[col],
            nbinsx=50,
            marker= dict(line =dict(width = 1, color ="black"))
        )
    )
    fig.update_layout(
        title=f"Distribution of {col}",
        xaxis_title=col,
        yaxis_title="Frequency",
        height=500
    )
    fig.add_vline(
    x=df[col].mean(),
    line_dash="dash",
    annotation_text="Mean"
    )
    
    fig.show()

In [17]:
for col in high_skewness:
    plot_frequency(col)

In [18]:
for col in high_skewness:
    df[col] = np.log1p(df[col])

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\1544914593.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [19]:
# After applying log tranformation lets visualize the graph again

for col in high_skewness:
    plot_frequency(col)

In [20]:
categorical_features = df.select_dtypes(include=["object"]).columns
categorical_features

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'ExterQual', 'ExterCond', 'Foundation', 'Heating',
       'HeatingQC', 'CentralAir', 'KitchenQual', 'Functional', 'PavedDrive',
       'SaleType', 'SaleCondition', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'GarageType',
       'GarageFinish', 'GarageQual', 'GarageCond'],
      dtype='object')

In [21]:
df[categorical_features].head()

,MSZoning,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,...,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageFinish,GarageQual,GarageCond
0,RL,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,Gd,TA,No,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA
1,RL,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,...,Gd,TA,Gd,ALQ,Unf,SBrkr,Attchd,RFn,TA,TA
2,RL,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,...,Gd,TA,Mn,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA
3,RL,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,...,TA,Gd,No,ALQ,Unf,SBrkr,Detchd,Unf,TA,TA
4,RL,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,...,Gd,TA,Av,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA

In [22]:
for col in categorical_features:
    print(df[col].value_counts())

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64
Street
Pave    1454
Grvl       6
Name: count, dtype: int64
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64
Utilities
AllPub    1459
NoSeWa       1
Name: count, dtype: int64
LotConfig
Inside     1052
Corner      263
CulDSac      94
FR2          47
FR3           4
Name: count, dtype: int64
LandSlope
Gtl    1382
Mod      65
Sev      13
Name: count, dtype: int64
Neighborhood
NAmes      225
CollgCr    150
OldTown    113
Edwards    100
Somerst     86
Gilbert     79
NridgHt     77
Sawyer      74
NWAmes      73
SawyerW     59
BrkSide     58
Crawfor     51
Mitchel     49
NoRidge     41
Timber      38
IDOTRR      37
ClearCr     28
StoneBr     25
SWISU       25
MeadowV     17
Blmngtn     17
BrDale      16
Veenker     11
NPkVill      9
Blueste      2
Name: count, dtype: int64
Condition1
Norm      1260
Feedr       81
Artery      48
RRAn        26
PosN        19
RRAe        11
PosA         8
RRNn         5
RRNe         2
Name: count, dtype: int64
Condition2
Norm      1445
Feedr        6
Artery       2
RRNn         2
PosN         2
PosA         1
RRAn         1
RRAe         1
Name: count, dtype: int64
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64
RoofMatl
CompShg    1434
Tar&Grv      11
WdShngl       6
WdShake       5
Metal         1
Membran       1
Roll          1
ClyTile       1
Name: count, dtype: int64
Exterior1st
VinylSd    515
HdBoard    222
MetalSd    220
Wd Sdng    206
Plywood    108
CemntBd     61
BrkFace     50
WdShing     26
Stucco      25
AsbShng     20
BrkComm      2
Stone        2
AsphShn      1
ImStucc      1
CBlock       1
Name: count, dtype: int64
Exterior2nd
VinylSd    504
MetalSd    214
HdBoard    207
Wd Sdng    197
Plywood    142
CmentBd     60
Wd Shng     38
Stucco      26
BrkFace     25
AsbShng     20
ImStucc     10
Brk Cmn      7
Stone        5
AsphShn      3
Other        1
CBlock       1
Name: count, dtype: int64
ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64
ExterCond
TA    1282
Gd     146
Fa      28
Ex       3
Po       1
Name: count, dtype: int64
Foundation
PConc     647
CBlock    634
BrkTil    146
Slab       24
Stone       6
Wood        3
Name: count, dtype: int64
Heating
GasA     1428
GasW       18
Grav        7
Wall        4
OthW        2
Floor       1
Name: count, dtype: int64
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64
CentralAir
Y    1365
N      95
Name: count, dtype: int64
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64
Functional
Typ     1360
Min2      34
Min1      31
Mod       15
Maj1      14
Maj2       5
Sev        1
Name: count, dtype: int64
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64
SaleType
WD       1267
New       122
COD        43
ConLD       9
ConLI       5
ConLw       5
CWD         4
Oth         3
Con         2
Name: count, dtype: int64
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64
BsmtQual
TA         649
Gd         618
Ex         121
unknown     37
Fa          35
Name: count, dtype: int64
BsmtCond
TA         1311
Gd           65
Fa           45
unknown      37
Po            2
Name: count, dtype: int64
BsmtExposure
No         953
Av         221
Gd         134
Mn         114
unknown     38
Name: count, dtype: int64
BsmtFinType1
Unf        430
GLQ        418
ALQ        220
BLQ        148
Rec        133
LwQ         74
unknown     37
Name: count, dtype: int64
BsmtFinType2
Unf        1256
Rec          54
LwQ          46
unknown      38
BLQ          33
ALQ          19
GLQ          14
Name: count, dtype: int64
Electrical
SBrkr      1334
FuseA        94
FuseF        27
FuseP         3
Mix           1
unknown       1
Name: count, dtype: int64
GarageType
Attchd     870
Detchd     387
BuiltIn     88
unknown     81
Basment     19
CarPort      9
2Types       6
Name: count, dtype: int64
GarageFinish
Unf        605
RFn        422
Fin        352
unknown     81
Name: count, dtype: int64
GarageQual
TA         1311
unknown      81
Fa           48
Gd           14
Ex            3
Po            3
Name: count, dtype: int64
GarageCond
TA         1326
unknown      81
Fa           35
Gd            9
Po            7
Ex            2
Name: count, dtype: int64

In [23]:
drop_cols = ["Utilities", "Street", "Condition2"]
categorical_features = categorical_features.drop(drop_cols)
categorical_features

Index(['MSZoning', 'LotShape', 'LandContour', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'BldgType', 'HouseStyle', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond',
       'Foundation', 'Heating', 'HeatingQC', 'CentralAir', 'KitchenQual',
       'Functional', 'PavedDrive', 'SaleType', 'SaleCondition', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'],
      dtype='object')

In [24]:
df[categorical_features]

,MSZoning,LotShape,LandContour,LotConfig,LandSlope,Neighborhood,Condition1,BldgType,HouseStyle,RoofStyle,...,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageFinish,GarageQual,GarageCond
0,RL,Reg,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,Gd,TA,No,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA
1,RL,Reg,Lvl,FR2,Gtl,Veenker,Feedr,1Fam,1Story,Gable,...,Gd,TA,Gd,ALQ,Unf,SBrkr,Attchd,RFn,TA,TA
2,RL,IR1,Lvl,Inside,Gtl,CollgCr,Norm,1Fam,2Story,Gable,...,Gd,TA,Mn,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA
3,RL,IR1,Lvl,Corner,Gtl,Crawfor,Norm,1Fam,2Story,Gable,...,TA,Gd,No,ALQ,Unf,SBrkr,Detchd,Unf,TA,TA
4,RL,IR1,Lvl,FR2,Gtl,NoRidge,Norm,1Fam,2Story,Gable,...,Gd,TA,Av,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,RL,Reg,Lvl,Inside,Gtl,Gilbert,Norm,1Fam,2Story,Gable,...,Gd,TA,No,Unf,Unf,SBrkr,Attchd,RFn,TA,TA
1456,RL,Reg,Lvl,Inside,Gtl,NWAmes,Norm,1Fam,1Story,Gable,...,Gd,TA,No,ALQ,Rec,SBrkr,Attchd,Unf,TA,TA
1457,RL,Reg,Lvl,Inside,Gtl,Crawfor,Norm,1Fam,2Story,Gable,...,TA,Gd,No,GLQ,Unf,SBrkr,Attchd,RFn,TA,TA
1458,RL,Reg,Lvl,Inside,Gtl,NAmes,Norm,1Fam,1Story,Hip,...,TA,TA,Mn,GLQ,Rec,FuseA,Attchd,Unf,TA,TA
1459,RL,Reg,Lvl,Inside,Gtl,Edwards,Norm,1Fam,1Story,Gable,...,TA,TA,No,BLQ,LwQ,SBrkr,Attchd,Fin,TA,TA

In [25]:
arr = ["CentralAir",

"PavedDrive" ,

"GarageFinish",

"BsmtExposure"]

for col in arr:
    print(df[col].value_counts())

CentralAir
Y    1365
N      95
Name: count, dtype: int64
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64
GarageFinish
Unf        605
RFn        422
Fin        352
unknown     81
Name: count, dtype: int64
BsmtExposure
No         953
Av         221
Gd         134
Mn         114
unknown     38
Name: count, dtype: int64

In [26]:
df["CentralAir"] = df["CentralAir"].map({"Y" : 1, "N" : 0})
df["PavedDrive"] = df["PavedDrive"].map({"Y" : 1, "N" : 0,"P" : -1})
df["GarageFinish"] = df["GarageFinish"].map({"Unf" : 0, "RFn" : 1, "Fin" : 2, "unknown" : -1})
df["BsmtExposure"] = df["BsmtExposure"].map({"No" : 0, "Av" : 1, "Gd" : 2, "Mn" : 3 , "unknown" : -1})
df[arr].head()

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\1185846802.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\1185846802.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\1185846802.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\1185846802.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   CentralAir  PavedDrive  GarageFinish  BsmtExposure
0           1           1             1             0
1           1           1             1             2
2           1           1             1             3
3           1           1             0             0
4           1           1             1             1

In [27]:
pd.set_option("display.max_columns",None)

In [28]:
df.head()

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond
0,1,4.110874,RL,9.042040,Pave,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,6.561031,0.0,150,6.753438,GasA,Ex,1,6.753438,854,0.0,7.444833,1,0.000000,2,1,3,0.693147,Gd,8,Typ,0,2,548,1,0.000000,4.127134,0.000000,0.0,0.0,0.0,0.0,2,2008,WD,Normal,12.247699,5.283204,Gd,TA,0,GLQ,Unf,SBrkr,Attchd,2003.0,1,TA,TA
1,2,3.044522,RL,9.169623,Pave,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,TA,TA,CBlock,6.886532,0.0,284,7.141245,GasA,Ex,1,7.141245,0,0.0,7.141245,0,0.693147,2,0,3,0.693147,TA,6,Typ,1,2,460,1,5.700444,0.000000,0.000000,0.0,0.0,0.0,0.0,5,2007,WD,Normal,12.109016,0.000000,Gd,TA,2,ALQ,Unf,SBrkr,Attchd,1976.0,1,TA,TA
2,3,4.110874,RL,9.328212,Pave,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,6.188264,0.0,434,6.825460,GasA,Ex,1,6.825460,866,0.0,7.488294,1,0.000000,2,1,3,0.693147,Gd,6,Typ,1,2,608,1,0.000000,3.761200,0.000000,0.0,0.0,0.0,0.0,9,2008,WD,Normal,12.317171,5.093750,Gd,TA,3,GLQ,Unf,SBrkr,Attchd,2001.0,1,TA,TA
3,4,4.262680,RL,9.164401,Pave,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,TA,TA,BrkTil,5.379897,0.0,540,6.629363,GasA,Gd,1,6.869014,756,0.0,7.448916,1,0.000000,1,0,3,0.693147,Gd,7,Typ,1,3,642,1,0.000000,3.583519,5.609472,0.0,0.0,0.0,0.0,2,2006,WD,Abnorml,11.849405,0.000000,TA,Gd,0,ALQ,Unf,SBrkr,Detchd,1998.0,0,TA,TA
4,5,4.110874,RL,9.565284,Pave,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,Gd,TA,PConc,6.486161,0.0,490,7.044033,GasA,Ex,1,7.044033,1053,0.0,7.695758,1,0.000000,2,1,4,0.693147,Gd,9,Typ,1,3,836,1,5.262690,4.442651,0.000000,0.0,0.0,0.0,0.0,12,2008,WD,Normal,12.429220,5.860786,Gd,TA,1,GLQ,Unf,SBrkr,Attchd,2000.0,1,TA,TA

In [29]:
arr1=["ExterQual",

"KitchenQual",

"HeatingQC",

"BsmtQual",

"GarageQual"]
for col in arr1:
    print(df[col].value_counts())

ExterQual
TA    906
Gd    488
Ex     52
Fa     14
Name: count, dtype: int64
KitchenQual
TA    735
Gd    586
Ex    100
Fa     39
Name: count, dtype: int64
HeatingQC
Ex    741
TA    428
Gd    241
Fa     49
Po      1
Name: count, dtype: int64
BsmtQual
TA         649
Gd         618
Ex         121
unknown     37
Fa          35
Name: count, dtype: int64
GarageQual
TA         1311
unknown      81
Fa           48
Gd           14
Ex            3
Po            3
Name: count, dtype: int64

In [30]:
qual_map = {
    "Po":1,
    "Fa":2,
    "TA":3,
    "Gd":4,
    "Ex":5,
    "unknown":0
}
for col in arr1:
    df[col] = df[col].map(qual_map)

df[arr1].head()

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2800577979.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2800577979.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2800577979.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2800577979.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\RITHIK KUMAR\AppData\Local\Temp\ipykernel_17768\2800577979.py:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   ExterQual  KitchenQual  HeatingQC  BsmtQual  GarageQual
0          4            4          5         4           3
1          3            3          5         4           3
2          4            4          5         4           3
3          3            4          4         3           3
4          4            4          5         4           3

In [31]:
arr2 = ["MSZoning",

"LotShape",

"LandContour",

"BldgType",

"HouseStyle",

"RoofStyle",

"SaleCondition"]

for col in arr2:
    print(df[col].value_counts())

MSZoning
RL         1151
RM          218
FV           65
RH           16
C (all)      10
Name: count, dtype: int64
LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64
LandContour
Lvl    1311
Bnk      63
HLS      50
Low      36
Name: count, dtype: int64
BldgType
1Fam      1220
TwnhsE     114
Duplex      52
Twnhs       43
2fmCon      31
Name: count, dtype: int64
HouseStyle
1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: count, dtype: int64
RoofStyle
Gable      1141
Hip         286
Flat         13
Gambrel      11
Mansard       7
Shed          2
Name: count, dtype: int64
SaleCondition
Normal     1198
Partial     125
Abnorml     101
Family       20
Alloca       12
AdjLand       4
Name: count, dtype: int64

In [32]:
df = pd.get_dummies(df, columns=arr2, drop_first=True)
df.head()

,Id,MSSubClass,LotArea,Street,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofMatl,Exterior1st,Exterior2nd,ExterQual,ExterCond,Foundation,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SalePrice,MasVnrArea,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageYrBlt,GarageFinish,GarageQual,GarageCond,MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,LotShape_IR2,LotShape_IR3,LotShape_Reg,LandContour_HLS,LandContour_Low,LandContour_Lvl,BldgType_2fmCon,BldgType_Duplex,BldgType_Twnhs,BldgType_TwnhsE,HouseStyle_1.5Unf,HouseStyle_1Story,HouseStyle_2.5Fin,HouseStyle_2.5Unf,HouseStyle_2Story,HouseStyle_SFoyer,HouseStyle_SLvl,RoofStyle_Gable,RoofStyle_Gambrel,RoofStyle_Hip,RoofStyle_Mansard,RoofStyle_Shed,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,4.110874,9.042040,Pave,AllPub,Inside,Gtl,CollgCr,Norm,Norm,7,5,2003,2003,CompShg,VinylSd,VinylSd,4,TA,PConc,6.561031,0.0,150,6.753438,GasA,5,1,6.753438,854,0.0,7.444833,1,0.000000,2,1,3,0.693147,4,8,Typ,0,2,548,1,0.000000,4.127134,0.000000,0.0,0.0,0.0,0.0,2,2008,WD,12.247699,5.283204,4,TA,0,GLQ,Unf,SBrkr,Attchd,2003.0,1,3,TA,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False
1,2,3.044522,9.169623,Pave,AllPub,FR2,Gtl,Veenker,Feedr,Norm,6,8,1976,1976,CompShg,MetalSd,MetalSd,3,TA,CBlock,6.886532,0.0,284,7.141245,GasA,5,1,7.141245,0,0.0,7.141245,0,0.693147,2,0,3,0.693147,3,6,Typ,1,2,460,1,5.700444,0.000000,0.000000,0.0,0.0,0.0,0.0,5,2007,WD,12.109016,0.000000,4,TA,2,ALQ,Unf,SBrkr,Attchd,1976.0,1,3,TA,False,False,True,False,False,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False
2,3,4.110874,9.328212,Pave,AllPub,Inside,Gtl,CollgCr,Norm,Norm,7,5,2001,2002,CompShg,VinylSd,VinylSd,4,TA,PConc,6.188264,0.0,434,6.825460,GasA,5,1,6.825460,866,0.0,7.488294,1,0.000000,2,1,3,0.693147,4,6,Typ,1,2,608,1,0.000000,3.761200,0.000000,0.0,0.0,0.0,0.0,9,2008,WD,12.317171,5.093750,4,TA,3,GLQ,Unf,SBrkr,Attchd,2001.0,1,3,TA,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False
3,4,4.262680,9.164401,Pave,AllPub,Corner,Gtl,Crawfor,Norm,Norm,7,5,1915,1970,CompShg,Wd Sdng,Wd Shng,3,TA,BrkTil,5.379897,0.0,540,6.629363,GasA,4,1,6.869014,756,0.0,7.448916,1,0.000000,1,0,3,0.693147,4,7,Typ,1,3,642,1,0.000000,3.583519,5.609472,0.0,0.0,0.0,0.0,2,2006,WD,11.849405,0.000000,3,Gd,0,ALQ,Unf,SBrkr,Detchd,1998.0,0,3,TA,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False
4,5,4.110874,9.565284,Pave,AllPub,FR2,Gtl,NoRidge,Norm,Norm,8,5,2000,2000,CompShg,VinylSd,VinylSd,4,TA,PConc,6.486161,0.0,490,7.044033,GasA,5,1,7.044033,1053,0.0,7.695758,1,0.000000,2,1,4,0.693147,4,9,Typ,1,3,836,1,5.262690,4.442651,0.000000,0.0,0.0,0.0,0.0,12,2008,WD,12.429220,5.860786,4,TA,1,GLQ,Unf,SBrkr,Attchd,2000.0,1,3,TA,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,True,False

In [33]:
new_cat_features = df.select_dtypes(include=["object"]).columns
df[new_cat_features][456:480]

,Street,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,RoofMatl,Exterior1st,Exterior2nd,ExterCond,Foundation,Heating,Functional,SaleType,BsmtCond,BsmtFinType1,BsmtFinType2,Electrical,GarageType,GarageCond
456,Pave,AllPub,Inside,Gtl,OldTown,Norm,Norm,CompShg,AsbShng,AsbShng,TA,BrkTil,GasA,Typ,COD,TA,Unf,Unf,SBrkr,Detchd,Fa
457,Pave,AllPub,CulDSac,Mod,ClearCr,Norm,Norm,Tar&Grv,Plywood,Plywood,TA,CBlock,GasA,Min1,WD,TA,BLQ,Unf,SBrkr,Attchd,TA
458,Pave,AllPub,Inside,Gtl,OldTown,Norm,Norm,CompShg,Stucco,Wd Shng,Gd,PConc,GasA,Typ,WD,TA,Unf,Unf,SBrkr,Detchd,TA
459,Pave,AllPub,Corner,Gtl,BrkSide,Norm,Norm,CompShg,MetalSd,MetalSd,TA,CBlock,GasA,Typ,WD,TA,LwQ,Unf,SBrkr,Detchd,TA
460,Pave,AllPub,Inside,Gtl,Somerst,RRAn,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,New,TA,GLQ,Unf,SBrkr,BuiltIn,TA
461,Pave,AllPub,Inside,Gtl,SWISU,Feedr,Norm,CompShg,Wd Sdng,Wd Sdng,Gd,PConc,GasA,Typ,WD,Gd,ALQ,BLQ,SBrkr,Detchd,TA
462,Pave,AllPub,Inside,Gtl,Sawyer,Norm,Norm,CompShg,MetalSd,MetalSd,TA,CBlock,GasA,Typ,WD,TA,Rec,BLQ,SBrkr,Detchd,TA
463,Pave,AllPub,Inside,Mod,Crawfor,Norm,Norm,CompShg,Stucco,Stucco,TA,CBlock,GasA,Typ,WD,TA,LwQ,Unf,FuseA,Detchd,TA
464,Pave,AllPub,Inside,Mod,CollgCr,Norm,Norm,CompShg,HdBoard,HdBoard,TA,CBlock,GasA,Typ,WD,TA,Rec,Unf,SBrkr,unknown,unknown
465,Pave,AllPub,Inside,Gtl,Blmngtn,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,WD,TA,Unf,Unf,SBrkr,Attchd,TA
466,Pave,AllPub,Inside,Gtl,NAmes,Norm,Norm,Tar&Grv,Plywood,Plywood,Gd,CBlock,GasA,Typ,WD,Gd,GLQ,Unf,SBrkr,Attchd,TA
467,Pave,AllPub,Inside,Gtl,NAmes,Artery,Norm,CompShg,MetalSd,MetalSd,TA,CBlock,GasA,Typ,WD,TA,LwQ,Unf,SBrkr,Attchd,TA
468,Pave,AllPub,Inside,Gtl,NridgHt,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,WD,TA,Unf,Unf,SBrkr,Attchd,TA
469,Pave,AllPub,Corner,Gtl,SawyerW,RRNe,Norm,CompShg,HdBoard,HdBoard,TA,PConc,GasA,Typ,WD,TA,GLQ,Unf,SBrkr,Attchd,TA
470,Pave,AllPub,Corner,Gtl,StoneBr,Norm,Norm,CompShg,HdBoard,HdBoard,TA,PConc,GasA,Typ,WD,TA,GLQ,BLQ,SBrkr,Attchd,TA
471,Pave,AllPub,Inside,Gtl,NWAmes,PosA,Norm,WdShake,WdShing,Plywood,TA,CBlock,GasA,Typ,WD,TA,Unf,Unf,SBrkr,Attchd,TA
472,Pave,AllPub,Inside,Gtl,Edwards,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,WD,TA,GLQ,Unf,SBrkr,Basment,TA
473,Pave,AllPub,Inside,Gtl,NridgHt,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,New,TA,GLQ,Unf,SBrkr,Attchd,TA
474,Pave,AllPub,Inside,Gtl,StoneBr,Norm,Norm,CompShg,CemntBd,CmentBd,TA,PConc,GasA,Typ,WD,TA,GLQ,Unf,SBrkr,Attchd,TA
475,Pave,AllPub,Corner,Gtl,Sawyer,Norm,Norm,CompShg,HdBoard,HdBoard,TA,CBlock,GasA,Typ,WD,TA,GLQ,Unf,SBrkr,Detchd,TA
476,Pave,AllPub,Inside,Mod,CollgCr,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,WD,TA,GLQ,Unf,SBrkr,Attchd,TA
477,Pave,AllPub,Inside,Gtl,NridgHt,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,WD,TA,Unf,Unf,SBrkr,BuiltIn,TA
478,Pave,AllPub,Inside,Gtl,CollgCr,Norm,Norm,CompShg,VinylSd,VinylSd,TA,PConc,GasA,Typ,WD,TA,GLQ,Unf,SBrkr,Attchd,TA
479,Pave,AllPub,Inside,Gtl,OldTown,Norm,Norm,CompShg,Stucco,Stucco,TA,BrkTil,GasA,Typ,WD,TA,Rec,Unf,SBrkr,Detchd,TA

In [34]:
df = df.drop(columns=drop_cols)
df.columns

Index(['Id', 'MSSubClass', 'LotArea', 'LotConfig', 'LandSlope', 'Neighborhood',
       'Condition1', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'ExterQual', 'ExterCond',
       'Foundation', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF',
       'Heating', 'HeatingQC', 'CentralAir', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageCars', 'GarageArea',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SalePrice', 'MasVnrArea', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageQual', 'GarageCond',
       'MSZoning_FV', 'MSZoning_RH', 'MSZoning_RL', 'MSZoning_RM',
       'LotShape_IR2', 'LotShape_IR3', 'LotShape_Reg', 'LandContour_HLS',
       'LandContour_Low', 'LandContour_Lvl', 'BldgType_2fmCon',
       'BldgType_Duplex', 'BldgType_Twnhs', 'BldgType_TwnhsE',
       'HouseStyle_1.5Unf', 'HouseStyle_1Story', 'HouseStyle_2.5Fin',
       'HouseStyle_2.5Unf', 'HouseStyle_2Story', 'HouseStyle_SFoyer',
       'HouseStyle_SLvl', 'RoofStyle_Gable', 'RoofStyle_Gambrel',
       'RoofStyle_Hip', 'RoofStyle_Mansard', 'RoofStyle_Shed',
       'SaleCondition_AdjLand', 'SaleCondition_Alloca', 'SaleCondition_Family',
       'SaleCondition_Normal', 'SaleCondition_Partial'],
      dtype='object')

In [35]:
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import StandardScaler

def preprocess_train(df):

    df = pd.read_csv(r"C:\potfolio\Advance_house_price_prediction\data\raw\train.csv")

    # Drop
    df.drop(columns=["Id"], inplace=True, errors="ignore")

    # -------- Ordinal Encoding --------
    qual_map = {"Po":1,"Fa":2,"TA":3,"Gd":4,"Ex":5,"unknown":0}
    bsmt_map = {"Unf":0,"LwQ":1,"Rec":2,"BLQ":3,"ALQ":4,"GLQ":5,"unknown":-1}
    func_map = {"Sev":1,"Maj2":2,"Maj1":3,"Mod":4,"Min2":5,"Min1":6,"Typ":7}

    for col in ["ExterCond","BsmtCond"]:
        if col in df.columns:
            df[col] = df[col].map(qual_map)

    if "BsmtFinType1" in df.columns:
        df["BsmtFinType1"] = df["BsmtFinType1"].map(bsmt_map)

    if "BsmtFinType2" in df.columns:
        df["BsmtFinType2"] = df["BsmtFinType2"].map(bsmt_map)

    if "Functional" in df.columns:
        df["Functional"] = df["Functional"].map(func_map)

    # -------- Target Encoding --------
    neigh_map = df.groupby("Neighborhood")["SalePrice"].mean()
    df["Neighborhood"] = df["Neighborhood"].map(neigh_map)

    # -------- Rare Handling --------
    freq = df["RoofMatl"].value_counts()
    rare = freq[freq < 10].index
    df["RoofMatl"] = df["RoofMatl"].replace(rare,"Other")

    # -------- Combine Exterior --------
    df["Exterior"] = df["Exterior1st"] + "_" + df["Exterior2nd"]
    df.drop(columns=["Exterior1st","Exterior2nd"], inplace=True)

    # -------- One-hot --------
    df = pd.get_dummies(df, drop_first=True)

    # -------- Separate --------
    y = np.log1p(df["SalePrice"])
    X = df.drop(columns=["SalePrice"])

    # -------- Scale --------
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Save artifacts
    joblib.dump(scaler, "scaler.pkl")
    joblib.dump(neigh_map, "neighborhood_map.pkl")
    joblib.dump(X.columns, "train_columns.pkl")

    # Save processed train
    train_df = pd.DataFrame(X_scaled, columns=X.columns)
    train_df["SalePrice"] = y.values
    train_df.to_csv(r"C:\potfolio\Advance_house_price_prediction\data\processed_data\processed_train.csv", index=False)

    return train_df

In [36]:
print(preprocess_train(df))

      MSSubClass  LotFrontage   LotArea  Neighborhood  OverallQual  \
0       0.073375    -0.208034 -0.207142      0.290573     0.651479
1      -0.872563     0.409895 -0.091886      0.986242    -0.071836
2       0.073375    -0.084449  0.073480      0.290573     0.651479
3       0.309859    -0.414011 -0.096897      0.506380     0.651479
4       0.073375     0.574676  0.375148      2.631741     1.374795
...          ...          ...       ...           ...          ...
1455    0.073375    -0.331620 -0.260560      0.203437    -0.071836
1456   -0.872563     0.615871  0.266407      0.138579    -0.071836
1457    0.309859    -0.166839 -0.147810      0.506380     0.651479
1458   -0.872563    -0.084449 -0.080160     -0.597937    -0.795151
1459   -0.872563     0.203918 -0.058112     -0.898445    -0.795151

      OverallCond  YearBuilt  YearRemodAdd  MasVnrArea  ExterCond  BsmtCond  \
0       -0.517200   1.050994      0.878668    0.510015  -0.238112 -0.039076
1        2.179628   0.156734     -0.429577   -0.572835  -0.238112 -0.039076
2       -0.517200   0.984752      0.830215    0.322174  -0.238112 -0.039076
3       -0.517200  -1.863632     -0.720298   -0.572835  -0.238112  3.436228
4       -0.517200   0.951632      0.733308    1.360826  -0.238112 -0.039076
...           ...        ...           ...         ...        ...       ...
1455    -0.517200   0.918511      0.733308   -0.572835  -0.238112 -0.039076
1456     0.381743   0.222975      0.151865    0.084610  -0.238112 -0.039076
1457     3.078570  -1.002492      1.024029   -0.572835   2.611429  3.436228
1458     0.381743  -0.704406      0.539493   -0.572835  -0.238112 -0.039076
1459     0.381743  -0.207594     -0.962566   -0.572835  -0.238112 -0.039076

      BsmtFinType1  BsmtFinSF1  BsmtFinType2  BsmtFinSF2  BsmtUnfSF  \
0         1.149803    0.575425     -0.318875   -0.288653  -0.944591
1         0.662993    1.171992     -0.318875   -0.288653  -0.641228
2         1.149803    0.092907     -0.318875   -0.288653  -0.301643
3         0.662993   -0.499274     -0.318875   -0.288653  -0.061670
4         1.149803    0.463568     -0.318875   -0.288653  -0.174865
...            ...         ...           ...         ...        ...
1455     -1.284249   -0.973018     -0.318875   -0.288653   0.873321
1456      0.662993    0.759659      1.954009    0.722112   0.049262
1457      1.149803   -0.369871     -0.318875   -0.288653   0.701265
1458      1.149803   -0.865548      1.954009    6.092188  -1.284176
1459      0.176182    0.847389      0.817567    1.509640  -0.976285

      TotalBsmtSF  1stFlrSF  2ndFlrSF  LowQualFinSF  GrLivArea  BsmtFullBath  \
0       -0.459303 -0.793434  1.161852     -0.120242   0.370333      1.107810
1        0.466465  0.257140 -0.795163     -0.120242  -0.482512     -0.819964
2       -0.313369 -0.627826  1.189351     -0.120242   0.515013      1.107810
3       -0.687324 -0.521734  0.937276     -0.120242   0.383659      1.107810
4        0.199680 -0.045611  1.617877     -0.120242   1.299326      1.107810
...           ...       ...       ...           ...        ...           ...
1455    -0.238122 -0.542435  0.795198     -0.120242   0.250402     -0.819964
1456     1.104925  2.355701 -0.795163     -0.120242   1.061367      1.107810
1457     0.215641  0.065656  1.844744     -0.120242   1.569647     -0.819964
1458     0.046905 -0.218982 -0.795163     -0.120242  -0.832788      1.107810
1459     0.452784  0.241615 -0.795163     -0.120242  -0.493934      1.107810

      BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  KitchenAbvGr  \
0        -0.241061  0.789741  1.227585      0.163779     -0.211454
1         3.948809  0.789741 -0.761621      0.163779     -0.211454
2        -0.241061  0.789741  1.227585      0.163779     -0.211454
3        -0.241061 -1.026041 -0.761621      0.163779     -0.211454
4        -0.241061  0.789741  1.227585      1.390023     -0.211454
...            ...       ...       ...           ...           ...
1455     -0.241061  0.789741  1.227585      0.163779     -0.211454
1456     -0.241061  0.789741 -0.761621      0.163779     -0.211454
1457     -0.241061  0.789741 -0.761621      1.390023     -0.211454
1458     -0.241061 -1.026041 -0.761621     -1.062465     -0.211454
1459     -0.241061 -1.026041  1.227585      0.163779     -0.211454

      TotRmsAbvGrd  Functional  Fireplaces  GarageYrBlt  GarageCars  \
0         0.912210    0.237044   -0.951226     0.992426    0.311725
1        -0.318683    0.237044    0.600495    -0.101543    0.311725
2        -0.318683    0.237044    0.600495     0.911391    0.311725
3         0.296763    0.237044    0.600495     0.789839    1.650307
4         1.527656    0.237044    0.600495     0.870874    1.650307
...            ...         ...         ...          ...         ...
1455      0.296763    0.237044    0.600495     0.830356    0.311725
1456      0.296763   -1.261154    2.152216    -0.020508    0.311725
1457      1.527656    0.237044    2.152216    -1.519651   -1.026858
1458     -0.934130    0.237044   -0.951226    -1.154995   -1.026858
1459     -0.318683    0.237044   -0.951226    -0.547234   -1.026858

      GarageArea  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0       0.351000   -0.752176     0.216503      -0.359325  -0.116339
1      -0.060731    1.626195    -0.704483      -0.359325  -0.116339
2       0.631726   -0.752176    -0.070361      -0.359325  -0.116339
3       0.790804   -0.752176    -0.176048       4.092524  -0.116339
4       1.698485    0.780197     0.563760      -0.359325  -0.116339
...          ...         ...          ...            ...        ...
1455   -0.060731   -0.752176    -0.100558      -0.359325  -0.116339
1456    0.126420    2.033231    -0.704483      -0.359325  -0.116339
1457   -1.033914   -0.752176     0.201405      -0.359325  -0.116339
1458   -1.090059    2.168910    -0.704483       1.473789  -0.116339
1459   -0.921624    5.121921     0.322190      -0.359325  -0.116339

      ScreenPorch  PoolArea   MiscVal    MoSold    YrSold  MSZoning_FV  \
0       -0.270208 -0.068692 -0.087688 -1.599111  0.138777    -0.215859
1       -0.270208 -0.068692 -0.087688 -0.489110 -0.614439    -0.215859
2       -0.270208 -0.068692 -0.087688  0.990891  0.138777    -0.215859
3       -0.270208 -0.068692 -0.087688 -1.599111 -1.367655    -0.215859
4       -0.270208 -0.068692 -0.087688  2.100892  0.138777    -0.215859
...           ...       ...       ...       ...       ...          ...
1455    -0.270208 -0.068692 -0.087688  0.620891 -0.614439    -0.215859
1456    -0.270208 -0.068692 -0.087688 -1.599111  1.645210    -0.215859
1457    -0.270208 -0.068692  4.953112 -0.489110  1.645210    -0.215859
1458    -0.270208 -0.068692 -0.087688 -0.859110  1.645210    -0.215859
1459    -0.270208 -0.068692 -0.087688 -0.119110  0.138777    -0.215859

      MSZoning_RH  MSZoning_RL  MSZoning_RM  Street_Pave  Alley_Pave  \
0       -0.105263     0.518133    -0.418955     0.064238   -0.169981
1       -0.105263     0.518133    -0.418955     0.064238   -0.169981
2       -0.105263     0.518133    -0.418955     0.064238   -0.169981
3       -0.105263     0.518133    -0.418955     0.064238   -0.169981
4       -0.105263     0.518133    -0.418955     0.064238   -0.169981
...           ...          ...          ...          ...         ...
1455    -0.105263     0.518133    -0.418955     0.064238   -0.169981
1456    -0.105263     0.518133    -0.418955     0.064238   -0.169981
1457    -0.105263     0.518133    -0.418955     0.064238   -0.169981
1458    -0.105263     0.518133    -0.418955     0.064238   -0.169981
1459    -0.105263     0.518133    -0.418955     0.064238   -0.169981

      LotShape_IR2  LotShape_IR3  LotShape_Reg  LandContour_HLS  \
0        -0.169981     -0.083045      0.760512        -0.188311
1        -0.169981     -0.083045      0.760512        -0.188311
2        -0.169981     -0.083045     -1.314904        -0.188311
3        -0.169981     -0.083045     -1.314904        -0.188311
4        -0.169981     -0.083045     -1.314904        -0.188311
...            ...           ...           ...              ...
1455     -0.169981     -0.083045      0.760512        -0.188311
1456     -0.169981     -0.083045      0.760512        -0.188311
1457     -0.169981     -0.083045      0.760512        -0.188311
1458     -0.169981     -0.083045      0.760512        -0.188311
1459     -0.169981     -0.083045      0.760512        -0.188311

      LandContour_Low  LandContour_Lvl  Utilities_NoSeWa  LotConfig_CulDSac  \
0              -0.159         0.337126          -0.02618          -0.262324
1              -0.159         0.337126          -0.02618          -0.262324
2              -0.159         0.337126          -0.02618          -0.262324
3              -0.159         0.337126          -0.02618          -0.262324
4              -0.159         0.337126          -0.02618          -0.262324
...               ...              ...               ...                ...
1455           -0.159         0.337126          -0.02618          -0.262324
1456           -0.159         0.337126          -0.02618          -0.262324
1457           -0.159         0.337126          -0.02618          -0.262324
1458           -0.159         0.337126          -0.02618          -0.262324
1459           -0.159         0.337126          -0.02618          -0.262324

      LotConfig_FR2  LotConfig_FR3  LotConfig_Inside  LandSlope_Mod  \
0         -0.182380      -0.052414          0.622762      -0.215859
1          5.483049      -0.052414         -1.605749      -0.215859
2         -0.182380      -0.052414          0.622762      -0.215859
3         -0.182380      -0.052414         -1.605749      -0.215859
4          5.483049      -0.052414         -1.605749      -0.215859
...             ...            ...               ...            ...
1455      -0.182380      -0.052414          0.622762      -0.215859
1456      -0.182380      -0.052414          0.622762      -0.215859
1457      -0.182380      -0.052414          0.622762      -0.215859
1458      -0.182380      -0.052414          0.622762      -0.215859
1459      -0.182380      -0.052414          0.622762      -0.215859

      LandSlope_Sev  Condition1_Feedr  Condition1_Norm  Condition1_PosA  \
0         -0.094785         -0.242360          0.39841        -0.074227
1         -0.094785          4.126099         -2.50998        -0.074227
2         -0.094785         -0.242360          0.39841        -0.074227
3         -0.094785         -0.242360          0.39841        -0.074227
4         -0.094785         -0.242360          0.39841        -0.074227
...             ...               ...              ...              ...
1455      -0.094785         -0.242360          0.39841        -0.074227
1456      -0.094785         -0.242360          0.39841        -0.074227
1457      -0.094785         -0.242360          0.39841        -0.074227
1458      -0.094785         -0.242360          0.39841        -0.074227
1459      -0.094785         -0.242360          0.39841        -0.074227

      Condition1_PosN  Condition1_RRAe  Condition1_RRAn  Condition1_RRNe  \
0           -0.114827        -0.087129        -0.134652        -0.037037
1           -0.114827        -0.087129        -0.134652        -0.037037
2           -0.114827        -0.087129        -0.134652        -0.037037
3           -0.114827        -0.087129        -0.134652        -0.037037
4           -0.114827        -0.087129        -0.134652        -0.037037
...               ...              ...              ...              ...
1455        -0.114827        -0.087129        -0.134652        -0.037037
1456        -0.114827        -0.087129        -0.134652        -0.037037
1457        -0.114827        -0.087129        -0.134652        -0.037037
1458        -0.114827        -0.087129        -0.134652        -0.037037
1459        -0.114827        -0.087129        -0.134652        -0.037037

      Condition1_RRNn  Condition2_Feedr  Condition2_Norm  Condition2_PosA  \
0           -0.058621         -0.064238         0.101885         -0.02618
1           -0.058621         -0.064238         0.101885         -0.02618
2           -0.058621         -0.064238         0.101885         -0.02618
3           -0.058621         -0.064238         0.101885         -0.02618
4           -0.058621         -0.064238         0.101885         -0.02618
...               ...               ...              ...              ...
1455        -0.058621         -0.064238         0.101885         -0.02618
1456        -0.058621         -0.064238         0.101885         -0.02618
1457        -0.058621         -0.064238         0.101885         -0.02618
1458        -0.058621         -0.064238         0.101885         -0.02618
1459        -0.058621         -0.064238         0.101885         -0.02618

      Condition2_PosN  Condition2_RRAe  Condition2_RRAn  Condition2_RRNn  \
0           -0.037037         -0.02618         -0.02618        -0.037037
1           -0.037037         -0.02618         -0.02618        -0.037037
2           -0.037037         -0.02618         -0.02618        -0.037037
3           -0.037037         -0.02618         -0.02618        -0.037037
4           -0.037037         -0.02618         -0.02618        -0.037037
...               ...              ...              ...              ...
1455        -0.037037         -0.02618         -0.02618        -0.037037
1456        -0.037037         -0.02618         -0.02618        -0.037037
1457        -0.037037         -0.02618         -0.02618        -0.037037
1458        -0.037037         -0.02618         -0.02618        -0.037037
1459        -0.037037         -0.02618         -0.02618        -0.037037

      BldgType_2fmCon  BldgType_Duplex  BldgType_Twnhs  BldgType_TwnhsE  \
0           -0.147287        -0.192177         -0.1742        -0.291025
1           -0.147287        -0.192177         -0.1742        -0.291025
2           -0.147287        -0.192177         -0.1742        -0.291025
3           -0.147287        -0.192177         -0.1742        -0.291025
4           -0.147287        -0.192177         -0.1742        -0.291025
...               ...              ...             ...              ...
1455        -0.147287        -0.192177         -0.1742        -0.291025
1456        -0.147287        -0.192177         -0.1742        -0.291025
1457        -0.147287        -0.192177         -0.1742        -0.291025
1458        -0.147287        -0.192177         -0.1742        -0.291025
1459        -0.147287        -0.192177         -0.1742        -0.291025

      HouseStyle_1.5Unf  HouseStyle_1Story  HouseStyle_2.5Fin  \
0             -0.098397          -0.994535          -0.074227
1             -0.098397           1.005495          -0.074227
2             -0.098397          -0.994535          -0.074227
3             -0.098397          -0.994535          -0.074227
4             -0.098397          -0.994535          -0.074227
...                 ...                ...                ...
1455          -0.098397          -0.994535          -0.074227
1456          -0.098397           1.005495          -0.074227
1457          -0.098397          -0.994535          -0.074227
1458          -0.098397           1.005495          -0.074227
1459          -0.098397           1.005495          -0.074227

      HouseStyle_2.5Unf  HouseStyle_2Story  HouseStyle_SFoyer  \
0             -0.087129           1.510265           -0.16125
1             -0.087129          -0.662136           -0.16125
2             -0.087129           1.510265           -0.16125
3             -0.087129           1.510265           -0.16125
4             -0.087129           1.510265           -0.16125
...                 ...                ...                ...
1455          -0.087129           1.510265           -0.16125
1456          -0.087129          -0.662136           -0.16125
1457          -0.087129           1.510265           -0.16125
1458          -0.087129          -0.662136           -0.16125
1459          -0.087129          -0.662136           -0.16125

      HouseStyle_SLvl  RoofStyle_Gable  RoofStyle_Gambrel  RoofStyle_Hip  \
0           -0.215859         0.528753          -0.087129      -0.493570
1           -0.215859         0.528753          -0.087129      -0.493570
2           -0.215859         0.528753          -0.087129      -0.493570
3           -0.215859         0.528753          -0.087129      -0.493570
4           -0.215859         0.528753          -0.087129      -0.493570
...               ...              ...                ...            ...
1455        -0.215859         0.528753          -0.087129      -0.493570
1456        -0.215859         0.528753          -0.087129      -0.493570
1457        -0.215859         0.528753          -0.087129      -0.493570
1458        -0.215859        -1.891244          -0.087129       2.026054
1459        -0.215859         0.528753          -0.087129      -0.493570

      RoofStyle_Mansard  RoofStyle_Shed  RoofMatl_Other  RoofMatl_Tar&Grv  \
0             -0.069409       -0.037037       -0.101885         -0.087129
1             -0.069409       -0.037037       -0.101885         -0.087129
2             -0.069409       -0.037037       -0.101885         -0.087129
3             -0.069409       -0.037037       -0.101885         -0.087129
4             -0.069409       -0.037037       -0.101885         -0.087129
...                 ...             ...             ...               ...
1455          -0.069409       -0.037037       -0.101885         -0.087129
1456          -0.069409       -0.037037       -0.101885         -0.087129
1457          -0.069409       -0.037037       -0.101885         -0.087129
1458          -0.069409       -0.037037       -0.101885         -0.087129
1459          -0.069409       -0.037037       -0.101885         -0.087129

      MasVnrType_BrkFace  MasVnrType_Stone  ExterQual_Fa  ExterQual_Gd  \
0               1.510265         -0.309994     -0.098397      1.411313
1              -0.662136         -0.309994     -0.098397     -0.708560
2               1.510265         -0.309994     -0.098397      1.411313
3              -0.662136         -0.309994     -0.098397     -0.708560
4               1.510265         -0.309994     -0.098397      1.411313
...                  ...               ...           ...           ...
1455           -0.662136         -0.309994     -0.098397     -0.708560
1456           -0.662136          3.225872     -0.098397     -0.708560
1457           -0.662136         -0.309994     -0.098397     -0.708560
1458           -0.662136         -0.309994     -0.098397     -0.708560
1459           -0.662136         -0.309994     -0.098397      1.411313

      ExterQual_TA  Foundation_CBlock  Foundation_PConc  Foundation_Slab  \
0        -1.278819          -0.876102          1.120968        -0.129279
1         0.781971           1.141420         -0.892086        -0.129279
2        -1.278819          -0.876102          1.120968        -0.129279
3         0.781971          -0.876102         -0.892086        -0.129279
4        -1.278819          -0.876102          1.120968        -0.129279
...            ...                ...               ...              ...
1455      0.781971          -0.876102          1.120968        -0.129279
1456      0.781971           1.141420         -0.892086        -0.129279
1457     -1.278819          -0.876102         -0.892086        -0.129279
1458      0.781971           1.141420         -0.892086        -0.129279
1459     -1.278819           1.141420         -0.892086        -0.129279

      Foundation_Stone  Foundation_Wood  BsmtQual_Fa  BsmtQual_Gd  \
0            -0.064238        -0.045376    -0.156721     1.167244
1            -0.064238        -0.045376    -0.156721     1.167244
2            -0.064238        -0.045376    -0.156721     1.167244
3            -0.064238        -0.045376    -0.156721    -0.856719
4            -0.064238        -0.045376    -0.156721     1.167244
...                ...              ...          ...          ...

In [37]:
processed_df = pd.read_csv(r"C:\potfolio\Advance_house_price_prediction\data\processed_data\processed_train.csv")

corr = processed_df.corr()


fig = go.Figure()

fig.add_trace(
    go.Heatmap(
        z = corr.values,
        y = corr.columns,
        x = corr.columns,
        colorscale="RdBu",
        zmin=-1,
        zmax=1
    )
)
fig.update_layout(
    title="Correlation Heatmap",
    xaxis_title="Features",
    yaxis_title="Features",
    height = 1000,
    width = 1500
)

fig.show()